// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metaservice.proto

package lnrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetInfo2Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfo2Request) Reset()         { *m = GetInfo2Request{} }
func (m *GetInfo2Request) String() string { return proto.CompactTextString(m) }
func (*GetInfo2Request) ProtoMessage()    {}
func (*GetInfo2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{0}
}

func (m *GetInfo2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfo2Request.Unmarshal(m, b)
}
func (m *GetInfo2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfo2Request.Marshal(b, m, deterministic)
}
func (m *GetInfo2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfo2Request.Merge(m, src)
}
func (m *GetInfo2Request) XXX_Size() int {
	return xxx_messageInfo_GetInfo2Request.Size(m)
}
func (m *GetInfo2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfo2Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfo2Request proto.InternalMessageInfo

type NeutrinoBan struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Endtime              string   `protobuf:"bytes,3,opt,name=endtime,proto3" json:"endtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeutrinoBan) Reset()         { *m = NeutrinoBan{} }
func (m *NeutrinoBan) String() string { return proto.CompactTextString(m) }
func (*NeutrinoBan) ProtoMessage()    {}
func (*NeutrinoBan) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{1}
}

func (m *NeutrinoBan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeutrinoBan.Unmarshal(m, b)
}
func (m *NeutrinoBan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeutrinoBan.Marshal(b, m, deterministic)
}
func (m *NeutrinoBan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeutrinoBan.Merge(m, src)
}
func (m *NeutrinoBan) XXX_Size() int {
	return xxx_messageInfo_NeutrinoBan.Size(m)
}
func (m *NeutrinoBan) XXX_DiscardUnknown() {
	xxx_messageInfo_NeutrinoBan.DiscardUnknown(m)
}

var xxx_messageInfo_NeutrinoBan proto.InternalMessageInfo

func (m *NeutrinoBan) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NeutrinoBan) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *NeutrinoBan) GetEndtime() string {
	if m != nil {
		return m.Endtime
	}
	return ""
}

type NeutrinoQuery struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ReqNum               uint32   `protobuf:"varint,3,opt,name=req_num,json=reqNum,proto3" json:"req_num,omitempty"`
	CreateTime           uint32   `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastRequestTime      uint32   `protobuf:"varint,5,opt,name=last_request_time,json=lastRequestTime,proto3" json:"last_request_time,omitempty"`
	LastResponseTime     uint32   `protobuf:"varint,6,opt,name=last_response_time,json=lastResponseTime,proto3" json:"last_response_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeutrinoQuery) Reset()         { *m = NeutrinoQuery{} }
func (m *NeutrinoQuery) String() string { return proto.CompactTextString(m) }
func (*NeutrinoQuery) ProtoMessage()    {}
func (*NeutrinoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{2}
}

func (m *NeutrinoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeutrinoQuery.Unmarshal(m, b)
}
func (m *NeutrinoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeutrinoQuery.Marshal(b, m, deterministic)
}
func (m *NeutrinoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeutrinoQuery.Merge(m, src)
}
func (m *NeutrinoQuery) XXX_Size() int {
	return xxx_messageInfo_NeutrinoQuery.Size(m)
}
func (m *NeutrinoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_NeutrinoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_NeutrinoQuery proto.InternalMessageInfo

func (m *NeutrinoQuery) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *NeutrinoQuery) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *NeutrinoQuery) GetReqNum() uint32 {
	if m != nil {
		return m.ReqNum
	}
	return 0
}

func (m *NeutrinoQuery) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *NeutrinoQuery) GetLastRequestTime() uint32 {
	if m != nil {
		return m.LastRequestTime
	}
	return 0
}

func (m *NeutrinoQuery) GetLastResponseTime() uint32 {
	if m != nil {
		return m.LastResponseTime
	}
	return 0
}

type NeutrinoInfo struct {
	Peers                *PeerDesc      `protobuf:"bytes,1,opt,name=peers,proto3" json:"peers,omitempty"`
	Bans                 *NeutrinoBan   `protobuf:"bytes,2,opt,name=bans,proto3" json:"bans,omitempty"`
	Queries              *NeutrinoQuery `protobuf:"bytes,3,opt,name=queries,proto3" json:"queries,omitempty"`
	BlockHash            string         `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Height               int32          `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	BlockTimestamp       string         `protobuf:"bytes,6,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	IsSyncing            bool           `protobuf:"varint,7,opt,name=is_syncing,json=isSyncing,proto3" json:"is_syncing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *NeutrinoInfo) Reset()         { *m = NeutrinoInfo{} }
func (m *NeutrinoInfo) String() string { return proto.CompactTextString(m) }
func (*NeutrinoInfo) ProtoMessage()    {}
func (*NeutrinoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{3}
}

func (m *NeutrinoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeutrinoInfo.Unmarshal(m, b)
}
func (m *NeutrinoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeutrinoInfo.Marshal(b, m, deterministic)
}
func (m *NeutrinoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeutrinoInfo.Merge(m, src)
}
func (m *NeutrinoInfo) XXX_Size() int {
	return xxx_messageInfo_NeutrinoInfo.Size(m)
}
func (m *NeutrinoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NeutrinoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NeutrinoInfo proto.InternalMessageInfo

func (m *NeutrinoInfo) GetPeers() *PeerDesc {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *NeutrinoInfo) GetBans() *NeutrinoBan {
	if m != nil {
		return m.Bans
	}
	return nil
}

func (m *NeutrinoInfo) GetQueries() *NeutrinoQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *NeutrinoInfo) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *NeutrinoInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NeutrinoInfo) GetBlockTimestamp() string {
	if m != nil {
		return m.BlockTimestamp
	}
	return ""
}

func (m *NeutrinoInfo) GetIsSyncing() bool {
	if m != nil {
		return m.IsSyncing
	}
	return false
}

type InfoWalletResult struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ProtocolVersion      int32    `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	WalletVersion        int32    `protobuf:"varint,3,opt,name=wallet_version,json=walletVersion,proto3" json:"wallet_version,omitempty"`
	Balance              float32  `protobuf:"fixed32,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Blocks               int32    `protobuf:"varint,5,opt,name=blocks,proto3" json:"blocks,omitempty"`
	TimeOffset           int64    `protobuf:"varint,6,opt,name=time_offset,json=timeOffset,proto3" json:"time_offset,omitempty"`
	Connections          int32    `protobuf:"varint,7,opt,name=connections,proto3" json:"connections,omitempty"`
	Difficulty           float32  `protobuf:"fixed32,8,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	TestNet              bool     `protobuf:"varint,9,opt,name=test_net,json=testNet,proto3" json:"test_net,omitempty"`
	KeypoolOldest        int64    `protobuf:"varint,10,opt,name=keypool_oldest,json=keypoolOldest,proto3" json:"keypool_oldest,omitempty"`
	KeypoolSize          int32    `protobuf:"varint,11,opt,name=keypool_size,json=keypoolSize,proto3" json:"keypool_size,omitempty"`
	UnlockedUntil        int64    `protobuf:"varint,12,opt,name=unlocked_until,json=unlockedUntil,proto3" json:"unlocked_until,omitempty"`
	PayTxFee             float32  `protobuf:"fixed32,13,opt,name=pay_tx_fee,json=payTxFee,proto3" json:"pay_tx_fee,omitempty"`
	RelayFee             float32  `protobuf:"fixed32,14,opt,name=relay_fee,json=relayFee,proto3" json:"relay_fee,omitempty"`
	Errors               string   `protobuf:"bytes,15,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoWalletResult) Reset()         { *m = InfoWalletResult{} }
func (m *InfoWalletResult) String() string { return proto.CompactTextString(m) }
func (*InfoWalletResult) ProtoMessage()    {}
func (*InfoWalletResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{4}
}

func (m *InfoWalletResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoWalletResult.Unmarshal(m, b)
}
func (m *InfoWalletResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoWalletResult.Marshal(b, m, deterministic)
}
func (m *InfoWalletResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoWalletResult.Merge(m, src)
}
func (m *InfoWalletResult) XXX_Size() int {
	return xxx_messageInfo_InfoWalletResult.Size(m)
}
func (m *InfoWalletResult) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoWalletResult.DiscardUnknown(m)
}

var xxx_messageInfo_InfoWalletResult proto.InternalMessageInfo

func (m *InfoWalletResult) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *InfoWalletResult) GetProtocolVersion() int32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *InfoWalletResult) GetWalletVersion() int32 {
	if m != nil {
		return m.WalletVersion
	}
	return 0
}

func (m *InfoWalletResult) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *InfoWalletResult) GetBlocks() int32 {
	if m != nil {
		return m.Blocks
	}
	return 0
}

func (m *InfoWalletResult) GetTimeOffset() int64 {
	if m != nil {
		return m.TimeOffset
	}
	return 0
}

func (m *InfoWalletResult) GetConnections() int32 {
	if m != nil {
		return m.Connections
	}
	return 0
}

func (m *InfoWalletResult) GetDifficulty() float32 {
	if m != nil {
		return m.Difficulty
	}
	return 0
}

func (m *InfoWalletResult) GetTestNet() bool {
	if m != nil {
		return m.TestNet
	}
	return false
}

func (m *InfoWalletResult) GetKeypoolOldest() int64 {
	if m != nil {
		return m.KeypoolOldest
	}
	return 0
}

func (m *InfoWalletResult) GetKeypoolSize() int32 {
	if m != nil {
		return m.KeypoolSize
	}
	return 0
}

func (m *InfoWalletResult) GetUnlockedUntil() int64 {
	if m != nil {
		return m.UnlockedUntil
	}
	return 0
}

func (m *InfoWalletResult) GetPayTxFee() float32 {
	if m != nil {
		return m.PayTxFee
	}
	return 0
}

func (m *InfoWalletResult) GetRelayFee() float32 {
	if m != nil {
		return m.RelayFee
	}
	return 0
}

func (m *InfoWalletResult) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type WalletInfo struct {
	CurrentBlockHash      string            `protobuf:"bytes,1,opt,name=current_block_hash,json=currentBlockHash,proto3" json:"current_block_hash,omitempty"`
	CurrentHeight         int32             `protobuf:"varint,2,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	CurrentBlockTimestamp string            `protobuf:"bytes,3,opt,name=current_block_timestamp,json=currentBlockTimestamp,proto3" json:"current_block_timestamp,omitempty"`
	WalletVersion         int32             `protobuf:"varint,4,opt,name=wallet_version,json=walletVersion,proto3" json:"wallet_version,omitempty"`
	WalletStats           *WalletStats      `protobuf:"bytes,5,opt,name=wallet_stats,json=walletStats,proto3" json:"wallet_stats,omitempty"`
	InfoWrpcInfo          *InfoWalletResult `protobuf:"bytes,6,opt,name=info_wrpc_info,json=infoWrpcInfo,proto3" json:"info_wrpc_info,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}          `json:"-"`
	XXX_unrecognized      []byte            `json:"-"`
	XXX_sizecache         int32             `json:"-"`
}

func (m *WalletInfo) Reset()         { *m = WalletInfo{} }
func (m *WalletInfo) String() string { return proto.CompactTextString(m) }
func (*WalletInfo) ProtoMessage()    {}
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{5}
}

func (m *WalletInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletInfo.Unmarshal(m, b)
}
func (m *WalletInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletInfo.Marshal(b, m, deterministic)
}
func (m *WalletInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletInfo.Merge(m, src)
}
func (m *WalletInfo) XXX_Size() int {
	return xxx_messageInfo_WalletInfo.Size(m)
}
func (m *WalletInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WalletInfo proto.InternalMessageInfo

func (m *WalletInfo) GetCurrentBlockHash() string {
	if m != nil {
		return m.CurrentBlockHash
	}
	return ""
}

func (m *WalletInfo) GetCurrentHeight() int32 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

func (m *WalletInfo) GetCurrentBlockTimestamp() string {
	if m != nil {
		return m.CurrentBlockTimestamp
	}
	return ""
}

func (m *WalletInfo) GetWalletVersion() int32 {
	if m != nil {
		return m.WalletVersion
	}
	return 0
}

func (m *WalletInfo) GetWalletStats() *WalletStats {
	if m != nil {
		return m.WalletStats
	}
	return nil
}

func (m *WalletInfo) GetInfoWrpcInfo() *InfoWalletResult {
	if m != nil {
		return m.InfoWrpcInfo
	}
	return nil
}

type GetInfo2Responce struct {
	Neutrino             *NeutrinoInfo    `protobuf:"bytes,1,opt,name=neutrino,proto3" json:"neutrino,omitempty"`
	Wallet               *WalletInfo      `protobuf:"bytes,2,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Lightning            *GetInfoResponse `protobuf:"bytes,3,opt,name=lightning,proto3" json:"lightning,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetInfo2Responce) Reset()         { *m = GetInfo2Responce{} }
func (m *GetInfo2Responce) String() string { return proto.CompactTextString(m) }
func (*GetInfo2Responce) ProtoMessage()    {}
func (*GetInfo2Responce) Descriptor() ([]byte, []int) {
	return fileDescriptor_b3fb5294949b9545, []int{6}
}

func (m *GetInfo2Responce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfo2Responce.Unmarshal(m, b)
}
func (m *GetInfo2Responce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfo2Responce.Marshal(b, m, deterministic)
}
func (m *GetInfo2Responce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfo2Responce.Merge(m, src)
}
func (m *GetInfo2Responce) XXX_Size() int {
	return xxx_messageInfo_GetInfo2Responce.Size(m)
}
func (m *GetInfo2Responce) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfo2Responce.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfo2Responce proto.InternalMessageInfo

func (m *GetInfo2Responce) GetNeutrino() *NeutrinoInfo {
	if m != nil {
		return m.Neutrino
	}
	return nil
}

func (m *GetInfo2Responce) GetWallet() *WalletInfo {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func (m *GetInfo2Responce) GetLightning() *GetInfoResponse {
	if m != nil {
		return m.Lightning
	}
	return nil
}

func init() {
	proto.RegisterType((*GetInfo2Request)(nil), "lnrpc.GetInfo2Request")
	proto.RegisterType((*NeutrinoBan)(nil), "lnrpc.neutrino_ban")
	proto.RegisterType((*NeutrinoQuery)(nil), "lnrpc.neutrino_query")
	proto.RegisterType((*NeutrinoInfo)(nil), "lnrpc.neutrino_info")
	proto.RegisterType((*InfoWalletResult)(nil), "lnrpc.info_wallet_result")
	proto.RegisterType((*WalletInfo)(nil), "lnrpc.wallet_info")
	proto.RegisterType((*GetInfo2Responce)(nil), "lnrpc.GetInfo2Responce")
}

func init() { proto.RegisterFile("metaservice.proto", fileDescriptor_b3fb5294949b9545) }

var fileDescriptor_b3fb5294949b9545 = []byte{
	// 879 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x55, 0xdb, 0x8e, 0x1b, 0x45,
	0x10, 0x95, 0xbd, 0xeb, 0xcb, 0x94, 0xaf, 0x69, 0xc8, 0xee, 0x64, 0xb9, 0x2d, 0x16, 0x21, 0x21,
	0x0a, 0xbb, 0xc8, 0xa0, 0xbc, 0xf0, 0x80, 0x94, 0x07, 0x08, 0x48, 0x24, 0xd2, 0xec, 0x02, 0x12,
	0x2f, 0xa3, 0x76, 0xbb, 0xbc, 0x1e, 0xed, 0x4c, 0xf7, 0x6c, 0x77, 0x4f, 0x88, 0xf3, 0x15, 0x7c,
	0x05, 0x1f, 0xc1, 0x67, 0xf0, 0x2d, 0x7c, 0x00, 0xea, 0xea, 0x6e, 0xdb, 0xd9, 0xe5, 0xc1, 0xd2,
	0xd4, 0xa9, 0x33, 0xd5, 0x7d, 0x6a, 0x4e, 0x95, 0xe1, 0x5e, 0x85, 0x96, 0x1b, 0xd4, 0xaf, 0x0b,
	0x81, 0x67, 0xb5, 0x56, 0x56, 0xb1, 0x4e, 0x29, 0x75, 0x2d, 0x4e, 0x92, 0xfa, 0xda, 0x7a, 0xe4,
	0x24, 0xd1, 0xb5, 0xf0, 0x8f, 0xb3, 0x7b, 0x30, 0xf9, 0x01, 0xed, 0x8f, 0x72, 0xa5, 0xe6, 0x19,
	0xde, 0x34, 0x68, 0xec, 0xec, 0x12, 0x86, 0x12, 0x1b, 0xab, 0x0b, 0xa9, 0xf2, 0x05, 0x97, 0x8c,
	0xc1, 0x21, 0x5f, 0x2e, 0x75, 0xda, 0x3a, 0x6d, 0x3d, 0x4e, 0x32, 0x7a, 0x66, 0x47, 0xd0, 0xd5,
	0xc8, 0x8d, 0x92, 0x69, 0x9b, 0xd0, 0x10, 0xb1, 0x14, 0x7a, 0x28, 0x97, 0xb6, 0xa8, 0x30, 0x3d,
	0xa0, 0x44, 0x0c, 0x67, 0xff, 0xb4, 0x60, 0xbc, 0x2d, 0x7b, 0xd3, 0xa0, 0xde, 0xb8, 0xc2, 0x35,
	0xe2, 0xb6, 0xb0, 0x7b, 0x76, 0x05, 0x84, 0xaa, 0x2a, 0x2e, 0x97, 0xa1, 0x72, 0x0c, 0xd9, 0x31,
	0xf4, 0x34, 0xde, 0xe4, 0xb2, 0xa9, 0xa8, 0xf4, 0xc8, 0x9d, 0x79, 0xf3, 0xb2, 0xa9, 0xd8, 0x27,
	0x30, 0x10, 0x1a, 0xb9, 0xc5, 0x9c, 0xce, 0x3d, 0xa4, 0x24, 0x78, 0xe8, 0xb2, 0xa8, 0x90, 0x3d,
	0x81, 0x7b, 0x25, 0x37, 0x36, 0xd7, 0x5e, 0xa0, 0xa7, 0x75, 0x88, 0x36, 0x71, 0x89, 0x20, 0x9c,
	0xb8, 0x4f, 0x81, 0x05, 0xae, 0xa9, 0x95, 0x34, 0xa1, 0x66, 0x97, 0xc8, 0x53, 0x4f, 0xf6, 0x09,
	0xc7, 0x9e, 0xfd, 0xd9, 0x86, 0xd1, 0x56, 0x54, 0x21, 0x57, 0x8a, 0x7d, 0x0e, 0x1d, 0xa7, 0xc3,
	0x90, 0xa8, 0xc1, 0x7c, 0x7a, 0x46, 0xcd, 0x3f, 0x73, 0x58, 0xbe, 0x44, 0x23, 0x32, 0x9f, 0x66,
	0x8f, 0xe0, 0x70, 0xc1, 0xa5, 0x21, 0x91, 0x83, 0xf9, 0x7b, 0x81, 0xb6, 0xdf, 0xf7, 0x8c, 0x08,
	0xec, 0x1c, 0x7a, 0xae, 0x5b, 0x05, 0x1a, 0x92, 0x3d, 0x98, 0xdf, 0xbf, 0xcd, 0xa5, 0x66, 0x66,
	0x91, 0xc5, 0x3e, 0x02, 0x58, 0x94, 0x4a, 0x5c, 0xe7, 0x6b, 0x6e, 0xd6, 0xd4, 0x8d, 0x24, 0x4b,
	0x08, 0x79, 0xc1, 0xcd, 0xda, 0x7d, 0xb9, 0x35, 0x16, 0x57, 0x6b, 0x4b, 0x1d, 0xe8, 0x64, 0x21,
	0x62, 0x8f, 0x60, 0xe2, 0x5f, 0x73, 0x82, 0x8d, 0xe5, 0x55, 0x4d, 0xaa, 0x93, 0x6c, 0x4c, 0xf0,
	0x65, 0x44, 0x5d, 0xfd, 0xc2, 0xe4, 0x66, 0x23, 0x45, 0x21, 0xaf, 0xd2, 0xde, 0x69, 0xeb, 0x71,
	0x3f, 0x4b, 0x0a, 0x73, 0xe1, 0x81, 0xd9, 0xbf, 0x07, 0xc0, 0x5c, 0x27, 0xf2, 0x3f, 0x78, 0x59,
	0x22, 0x35, 0xb2, 0x29, 0xad, 0xfb, 0xae, 0xaf, 0x51, 0x9b, 0x42, 0x49, 0xea, 0x4c, 0x27, 0x8b,
	0x21, 0xfb, 0x02, 0xa6, 0x64, 0x45, 0xa1, 0xca, 0x3c, 0x52, 0xda, 0x44, 0x99, 0x44, 0xfc, 0xd7,
	0x40, 0x7d, 0x08, 0xe3, 0x50, 0x35, 0x12, 0x0f, 0x88, 0x38, 0xf2, 0x68, 0xa4, 0xa5, 0xd0, 0x5b,
	0xf0, 0x92, 0x4b, 0xe1, 0xcd, 0xd0, 0xce, 0x62, 0xe8, 0xc4, 0x93, 0x1a, 0x13, 0xc5, 0xfb, 0xc8,
	0x59, 0xc8, 0xc9, 0xce, 0xd5, 0x6a, 0x65, 0xd0, 0x92, 0xf0, 0x83, 0x0c, 0x1c, 0xf4, 0x8a, 0x10,
	0x76, 0x0a, 0x03, 0xa1, 0xa4, 0x44, 0x61, 0x0b, 0x25, 0x0d, 0xa9, 0xee, 0x64, 0xfb, 0x10, 0xfb,
	0x18, 0x60, 0x59, 0xac, 0x56, 0x85, 0x68, 0x4a, 0xbb, 0x49, 0xfb, 0x74, 0xee, 0x1e, 0xc2, 0x1e,
	0x40, 0xdf, 0x3a, 0xf3, 0x49, 0xb4, 0x69, 0x42, 0x4d, 0xeb, 0xb9, 0xf8, 0x25, 0x5a, 0x27, 0xeb,
	0x1a, 0x37, 0xb5, 0x52, 0x65, 0xae, 0xca, 0x25, 0x1a, 0x9b, 0x02, 0x5d, 0x60, 0x14, 0xd0, 0x57,
	0x04, 0xb2, 0x4f, 0x61, 0x18, 0x69, 0xa6, 0x78, 0x8b, 0xe9, 0xc0, 0x5f, 0x22, 0x60, 0x17, 0xc5,
	0x5b, 0x74, 0x95, 0x1a, 0xe9, 0x24, 0xe1, 0x32, 0x6f, 0xa4, 0x2d, 0xca, 0x74, 0xe8, 0x2b, 0x45,
	0xf4, 0x17, 0x07, 0xb2, 0x0f, 0x01, 0x6a, 0xbe, 0xc9, 0xed, 0x9b, 0x7c, 0x85, 0x98, 0x8e, 0xe8,
	0xae, 0xfd, 0x9a, 0x6f, 0x2e, 0xdf, 0x7c, 0x8f, 0xc8, 0x3e, 0x80, 0x44, 0x63, 0xc9, 0x37, 0x94,
	0x1c, 0xfb, 0x24, 0x01, 0x2e, 0x79, 0x04, 0x5d, 0xd4, 0x5a, 0x69, 0x93, 0x4e, 0xfc, 0xe0, 0xfb,
	0x68, 0xf6, 0x77, 0x1b, 0x06, 0xe1, 0xdb, 0xd0, 0x1c, 0x3c, 0x05, 0x26, 0x1a, 0xad, 0x51, 0xda,
	0x7c, 0xcf, 0x8d, 0x7e, 0xd2, 0xa7, 0x21, 0xf3, 0x7c, 0x6b, 0xca, 0x87, 0x30, 0x8e, 0xec, 0x60,
	0x4e, 0xef, 0x80, 0x51, 0x40, 0x5f, 0x78, 0x8f, 0x3e, 0x83, 0xe3, 0x77, 0x8b, 0xee, 0xbc, 0xea,
	0xb7, 0xcd, 0xfd, 0xfd, 0xca, 0x3b, 0xcb, 0xde, 0xf5, 0xcd, 0xe1, 0xff, 0xf9, 0xe6, 0x19, 0x0c,
	0x03, 0xcd, 0x58, 0x6e, 0xbd, 0x47, 0x76, 0xb3, 0xb9, 0x9f, 0xca, 0x82, 0xd6, 0x0b, 0x17, 0xb0,
	0xef, 0x60, 0xec, 0x1d, 0xaf, 0x6b, 0x41, 0xea, 0xc9, 0x40, 0x83, 0xf9, 0x83, 0xf0, 0xe6, 0xdd,
	0x71, 0xc8, 0x86, 0x0e, 0xfb, 0x4d, 0xd7, 0xc2, 0x6d, 0xde, 0xd9, 0x5f, 0x2d, 0x98, 0xee, 0xb6,
	0xb0, 0xdb, 0x2f, 0x02, 0xd9, 0x57, 0xd0, 0x8f, 0x23, 0x1e, 0x96, 0xc9, 0xfb, 0xb7, 0x27, 0xdf,
	0x15, 0xc9, 0xb6, 0x2c, 0xf6, 0x04, 0xba, 0xfe, 0x94, 0xb0, 0x55, 0xd8, 0xbb, 0x37, 0x27, 0x76,
	0x60, 0xb0, 0x6f, 0x20, 0x29, 0x5d, 0x4f, 0xa5, 0x1b, 0x62, 0xbf, 0x58, 0x8e, 0x02, 0x3d, 0xdc,
	0x24, 0x2e, 0xba, 0x6c, 0x47, 0x9c, 0xff, 0x04, 0x83, 0x9f, 0xd1, 0xf2, 0x0b, 0xff, 0xff, 0xc2,
	0xbe, 0x85, 0x7e, 0xbc, 0x36, 0xbb, 0xf5, 0x76, 0xfc, 0x37, 0x39, 0x39, 0xbe, 0x83, 0x7b, 0x7d,
	0xcf, 0x3f, 0xfb, 0x7d, 0x76, 0x55, 0xd8, 0x75, 0xb3, 0x38, 0x13, 0xaa, 0x3a, 0xaf, 0xaf, 0xed,
	0x97, 0x82, 0x9b, 0xb5, 0x7b, 0x58, 0x9e, 0x97, 0xd2, 0xfd, 0x74, 0x2d, 0x16, 0x5d, 0xda, 0x01,
	0x5f, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x79, 0xed, 0x33, 0xcf, 0xd8, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetaServiceClient is the client API for MetaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetaServiceClient interface {
	GetInfo2(ctx context.Context, in *GetInfo2Request, opts ...grpc.CallOption) (*GetInfo2Responce, error)
}

type metaServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetaServiceClient(cc *grpc.ClientConn) MetaServiceClient {
	return &metaServiceClient{cc}
}

func (c *metaServiceClient) GetInfo2(ctx context.Context, in *GetInfo2Request, opts ...grpc.CallOption) (*GetInfo2Responce, error) {
	out := new(GetInfo2Responce)
	err := c.cc.Invoke(ctx, "/lnrpc.MetaService/GetInfo2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaServiceServer is the server API for MetaService service.
type MetaServiceServer interface {
	GetInfo2(context.Context, *GetInfo2Request) (*GetInfo2Responce, error)
}

// UnimplementedMetaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetaServiceServer struct {
}

func (*UnimplementedMetaServiceServer) GetInfo2(ctx context.Context, req *GetInfo2Request) (*GetInfo2Responce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo2 not implemented")
}

func RegisterMetaServiceServer(s *grpc.Server, srv MetaServiceServer) {
	s.RegisterService(&_MetaService_serviceDesc, srv)
}

func _MetaService_GetInfo2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfo2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaServiceServer).GetInfo2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lnrpc.MetaService/GetInfo2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaServiceServer).GetInfo2(ctx, req.(*GetInfo2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lnrpc.MetaService",
	HandlerType: (*MetaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo2",
			Handler:    _MetaService_GetInfo2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metaservice.proto",
}
