// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkt.proto

package lnrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Config struct {
	UserAgentName        string   `protobuf:"bytes,3,opt,name=user_agent_name,json=userAgentName,proto3" json:"user_agent_name,omitempty"`
	UserAgentVersion     string   `protobuf:"bytes,4,opt,name=user_agent_version,json=userAgentVersion,proto3" json:"user_agent_version,omitempty"`
	UserAgentComments    []string `protobuf:"bytes,5,rep,name=user_agent_comments,json=userAgentComments,proto3" json:"user_agent_comments,omitempty"`
	Services             string   `protobuf:"bytes,7,opt,name=services,proto3" json:"services,omitempty"`
	ProtocolVersion      uint32   `protobuf:"varint,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	DisableRelayTx       bool     `protobuf:"varint,9,opt,name=disable_relay_tx,json=disableRelayTx,proto3" json:"disable_relay_tx,omitempty"`
	TrickleInterval      int64    `protobuf:"varint,11,opt,name=trickle_interval,json=trickleInterval,proto3" json:"trickle_interval,omitempty"`
	AllowSelfConns       bool     `protobuf:"varint,12,opt,name=allow_self_conns,json=allowSelfConns,proto3" json:"allow_self_conns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetUserAgentName() string {
	if m != nil {
		return m.UserAgentName
	}
	return ""
}

func (m *Config) GetUserAgentVersion() string {
	if m != nil {
		return m.UserAgentVersion
	}
	return ""
}

func (m *Config) GetUserAgentComments() []string {
	if m != nil {
		return m.UserAgentComments
	}
	return nil
}

func (m *Config) GetServices() string {
	if m != nil {
		return m.Services
	}
	return ""
}

func (m *Config) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *Config) GetDisableRelayTx() bool {
	if m != nil {
		return m.DisableRelayTx
	}
	return false
}

func (m *Config) GetTrickleInterval() int64 {
	if m != nil {
		return m.TrickleInterval
	}
	return 0
}

func (m *Config) GetAllowSelfConns() bool {
	if m != nil {
		return m.AllowSelfConns
	}
	return false
}

type PeerDesc struct {
	BytesReceived        uint64   `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BytesSent            uint64   `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	LastRecv             string   `protobuf:"bytes,3,opt,name=last_recv,json=lastRecv,proto3" json:"last_recv,omitempty"`
	LastSend             string   `protobuf:"bytes,4,opt,name=last_send,json=lastSend,proto3" json:"last_send,omitempty"`
	Connected            bool     `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	Addr                 string   `protobuf:"bytes,6,opt,name=addr,proto3" json:"addr,omitempty"`
	Cfg                  *Config  `protobuf:"bytes,7,opt,name=cfg,proto3" json:"cfg,omitempty"`
	Inbound              bool     `protobuf:"varint,8,opt,name=inbound,proto3" json:"inbound,omitempty"`
	Na                   string   `protobuf:"bytes,9,opt,name=na,proto3" json:"na,omitempty"`
	Id                   int32    `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	UserAgent            string   `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Services             string   `protobuf:"bytes,12,opt,name=services,proto3" json:"services,omitempty"`
	VersionKnown         bool     `protobuf:"varint,13,opt,name=version_known,json=versionKnown,proto3" json:"version_known,omitempty"`
	AdvertisedProtoVer   uint32   `protobuf:"varint,14,opt,name=advertised_proto_ver,json=advertisedProtoVer,proto3" json:"advertised_proto_ver,omitempty"`
	ProtocolVersion      uint32   `protobuf:"varint,15,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SendHeadersPreferred bool     `protobuf:"varint,16,opt,name=send_headers_preferred,json=sendHeadersPreferred,proto3" json:"send_headers_preferred,omitempty"`
	VerAckReceived       bool     `protobuf:"varint,17,opt,name=ver_ack_received,json=verAckReceived,proto3" json:"ver_ack_received,omitempty"`
	WitnessEnabled       bool     `protobuf:"varint,18,opt,name=witness_enabled,json=witnessEnabled,proto3" json:"witness_enabled,omitempty"`
	WireEncoding         string   `protobuf:"bytes,19,opt,name=wire_encoding,json=wireEncoding,proto3" json:"wire_encoding,omitempty"`
	TimeOffset           int64    `protobuf:"varint,20,opt,name=time_offset,json=timeOffset,proto3" json:"time_offset,omitempty"`
	TimeConnected        string   `protobuf:"bytes,21,opt,name=time_connected,json=timeConnected,proto3" json:"time_connected,omitempty"`
	StartingHeight       int32    `protobuf:"varint,22,opt,name=starting_height,json=startingHeight,proto3" json:"starting_height,omitempty"`
	LastBlock            int32    `protobuf:"varint,23,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	LastAnnouncedBlock   []byte   `protobuf:"bytes,24,opt,name=last_announced_block,json=lastAnnouncedBlock,proto3" json:"last_announced_block,omitempty"`
	LastPingNonce        uint64   `protobuf:"varint,25,opt,name=last_ping_nonce,json=lastPingNonce,proto3" json:"last_ping_nonce,omitempty"`
	LastPingTime         string   `protobuf:"bytes,26,opt,name=last_ping_time,json=lastPingTime,proto3" json:"last_ping_time,omitempty"`
	LastPingMicros       int64    `protobuf:"varint,27,opt,name=last_ping_micros,json=lastPingMicros,proto3" json:"last_ping_micros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerDesc) Reset()         { *m = PeerDesc{} }
func (m *PeerDesc) String() string { return proto.CompactTextString(m) }
func (*PeerDesc) ProtoMessage()    {}
func (*PeerDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{1}
}

func (m *PeerDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDesc.Unmarshal(m, b)
}
func (m *PeerDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDesc.Marshal(b, m, deterministic)
}
func (m *PeerDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDesc.Merge(m, src)
}
func (m *PeerDesc) XXX_Size() int {
	return xxx_messageInfo_PeerDesc.Size(m)
}
func (m *PeerDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDesc.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDesc proto.InternalMessageInfo

func (m *PeerDesc) GetBytesReceived() uint64 {
	if m != nil {
		return m.BytesReceived
	}
	return 0
}

func (m *PeerDesc) GetBytesSent() uint64 {
	if m != nil {
		return m.BytesSent
	}
	return 0
}

func (m *PeerDesc) GetLastRecv() string {
	if m != nil {
		return m.LastRecv
	}
	return ""
}

func (m *PeerDesc) GetLastSend() string {
	if m != nil {
		return m.LastSend
	}
	return ""
}

func (m *PeerDesc) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

func (m *PeerDesc) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PeerDesc) GetCfg() *Config {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *PeerDesc) GetInbound() bool {
	if m != nil {
		return m.Inbound
	}
	return false
}

func (m *PeerDesc) GetNa() string {
	if m != nil {
		return m.Na
	}
	return ""
}

func (m *PeerDesc) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PeerDesc) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *PeerDesc) GetServices() string {
	if m != nil {
		return m.Services
	}
	return ""
}

func (m *PeerDesc) GetVersionKnown() bool {
	if m != nil {
		return m.VersionKnown
	}
	return false
}

func (m *PeerDesc) GetAdvertisedProtoVer() uint32 {
	if m != nil {
		return m.AdvertisedProtoVer
	}
	return 0
}

func (m *PeerDesc) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *PeerDesc) GetSendHeadersPreferred() bool {
	if m != nil {
		return m.SendHeadersPreferred
	}
	return false
}

func (m *PeerDesc) GetVerAckReceived() bool {
	if m != nil {
		return m.VerAckReceived
	}
	return false
}

func (m *PeerDesc) GetWitnessEnabled() bool {
	if m != nil {
		return m.WitnessEnabled
	}
	return false
}

func (m *PeerDesc) GetWireEncoding() string {
	if m != nil {
		return m.WireEncoding
	}
	return ""
}

func (m *PeerDesc) GetTimeOffset() int64 {
	if m != nil {
		return m.TimeOffset
	}
	return 0
}

func (m *PeerDesc) GetTimeConnected() string {
	if m != nil {
		return m.TimeConnected
	}
	return ""
}

func (m *PeerDesc) GetStartingHeight() int32 {
	if m != nil {
		return m.StartingHeight
	}
	return 0
}

func (m *PeerDesc) GetLastBlock() int32 {
	if m != nil {
		return m.LastBlock
	}
	return 0
}

func (m *PeerDesc) GetLastAnnouncedBlock() []byte {
	if m != nil {
		return m.LastAnnouncedBlock
	}
	return nil
}

func (m *PeerDesc) GetLastPingNonce() uint64 {
	if m != nil {
		return m.LastPingNonce
	}
	return 0
}

func (m *PeerDesc) GetLastPingTime() string {
	if m != nil {
		return m.LastPingTime
	}
	return ""
}

func (m *PeerDesc) GetLastPingMicros() int64 {
	if m != nil {
		return m.LastPingMicros
	}
	return 0
}

type WalletStats struct {
	MaintenanceInProgress       bool     `protobuf:"varint,1,opt,name=maintenance_in_progress,json=maintenanceInProgress,proto3" json:"maintenance_in_progress,omitempty"`
	MaintenanceName             string   `protobuf:"bytes,2,opt,name=maintenance_name,json=maintenanceName,proto3" json:"maintenance_name,omitempty"`
	MaintenanceCycles           int32    `protobuf:"varint,3,opt,name=maintenance_cycles,json=maintenanceCycles,proto3" json:"maintenance_cycles,omitempty"`
	MaintenanceLastBlockVisited int32    `protobuf:"varint,4,opt,name=maintenance_last_block_visited,json=maintenanceLastBlockVisited,proto3" json:"maintenance_last_block_visited,omitempty"`
	TimeOfLastMaintenance       string   `protobuf:"bytes,5,opt,name=time_of_last_maintenance,json=timeOfLastMaintenance,proto3" json:"time_of_last_maintenance,omitempty"`
	Syncing                     bool     `protobuf:"varint,6,opt,name=syncing,proto3" json:"syncing,omitempty"`
	SyncStarted                 string   `protobuf:"bytes,7,opt,name=sync_started,json=syncStarted,proto3" json:"sync_started,omitempty"`
	SyncRemainingSeconds        int64    `protobuf:"varint,8,opt,name=sync_remaining_seconds,json=syncRemainingSeconds,proto3" json:"sync_remaining_seconds,omitempty"`
	SyncCurrentBlock            int32    `protobuf:"varint,9,opt,name=sync_current_block,json=syncCurrentBlock,proto3" json:"sync_current_block,omitempty"`
	SyncFrom                    int32    `protobuf:"varint,10,opt,name=sync_from,json=syncFrom,proto3" json:"sync_from,omitempty"`
	SyncTo                      int32    `protobuf:"varint,11,opt,name=sync_to,json=syncTo,proto3" json:"sync_to,omitempty"`
	BirthdayBlock               int32    `protobuf:"varint,12,opt,name=birthday_block,json=birthdayBlock,proto3" json:"birthday_block,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *WalletStats) Reset()         { *m = WalletStats{} }
func (m *WalletStats) String() string { return proto.CompactTextString(m) }
func (*WalletStats) ProtoMessage()    {}
func (*WalletStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{2}
}

func (m *WalletStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletStats.Unmarshal(m, b)
}
func (m *WalletStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletStats.Marshal(b, m, deterministic)
}
func (m *WalletStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletStats.Merge(m, src)
}
func (m *WalletStats) XXX_Size() int {
	return xxx_messageInfo_WalletStats.Size(m)
}
func (m *WalletStats) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletStats.DiscardUnknown(m)
}

var xxx_messageInfo_WalletStats proto.InternalMessageInfo

func (m *WalletStats) GetMaintenanceInProgress() bool {
	if m != nil {
		return m.MaintenanceInProgress
	}
	return false
}

func (m *WalletStats) GetMaintenanceName() string {
	if m != nil {
		return m.MaintenanceName
	}
	return ""
}

func (m *WalletStats) GetMaintenanceCycles() int32 {
	if m != nil {
		return m.MaintenanceCycles
	}
	return 0
}

func (m *WalletStats) GetMaintenanceLastBlockVisited() int32 {
	if m != nil {
		return m.MaintenanceLastBlockVisited
	}
	return 0
}

func (m *WalletStats) GetTimeOfLastMaintenance() string {
	if m != nil {
		return m.TimeOfLastMaintenance
	}
	return ""
}

func (m *WalletStats) GetSyncing() bool {
	if m != nil {
		return m.Syncing
	}
	return false
}

func (m *WalletStats) GetSyncStarted() string {
	if m != nil {
		return m.SyncStarted
	}
	return ""
}

func (m *WalletStats) GetSyncRemainingSeconds() int64 {
	if m != nil {
		return m.SyncRemainingSeconds
	}
	return 0
}

func (m *WalletStats) GetSyncCurrentBlock() int32 {
	if m != nil {
		return m.SyncCurrentBlock
	}
	return 0
}

func (m *WalletStats) GetSyncFrom() int32 {
	if m != nil {
		return m.SyncFrom
	}
	return 0
}

func (m *WalletStats) GetSyncTo() int32 {
	if m != nil {
		return m.SyncTo
	}
	return 0
}

func (m *WalletStats) GetBirthdayBlock() int32 {
	if m != nil {
		return m.BirthdayBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*Config)(nil), "lnrpc.Config")
	proto.RegisterType((*PeerDesc)(nil), "lnrpc.PeerDesc")
	proto.RegisterType((*WalletStats)(nil), "lnrpc.WalletStats")
}

func init() { proto.RegisterFile("pkt.proto", fileDescriptor_3c5f63a845a51abc) }

var fileDescriptor_3c5f63a845a51abc = []byte{
	// 989 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x95, 0xdf, 0x6e, 0x1b, 0x45,
	0x14, 0xc6, 0x65, 0x27, 0x4e, 0xbd, 0x13, 0xff, 0x49, 0xa6, 0x49, 0x33, 0x34, 0x40, 0x4d, 0x28,
	0xad, 0x91, 0x68, 0x8a, 0x00, 0xc1, 0x75, 0x6a, 0x8a, 0x5a, 0x41, 0x4b, 0xb4, 0x8e, 0x82, 0xc4,
	0xcd, 0x6a, 0x3c, 0x7b, 0x6c, 0x8f, 0xbc, 0x3b, 0x63, 0xcd, 0x4c, 0x9c, 0xfa, 0x59, 0x78, 0x15,
	0x1e, 0x83, 0x07, 0x42, 0xe7, 0xcc, 0xae, 0x6d, 0x50, 0x2f, 0x2c, 0xed, 0xfe, 0xbe, 0x6f, 0xfe,
	0xec, 0x9c, 0x6f, 0x8e, 0x59, 0xb2, 0x5c, 0x84, 0xcb, 0xa5, 0xb3, 0xc1, 0xf2, 0x56, 0x61, 0xdc,
	0x52, 0x5d, 0xfc, 0xd3, 0x64, 0x07, 0x23, 0x6b, 0xa6, 0x7a, 0xc6, 0x9f, 0xb1, 0xfe, 0x9d, 0x07,
	0x97, 0xc9, 0x19, 0x98, 0x90, 0x19, 0x59, 0x82, 0xd8, 0x1b, 0x34, 0x86, 0x49, 0xda, 0x45, 0x7c,
	0x85, 0xf4, 0xbd, 0x2c, 0x81, 0x7f, 0xc3, 0xf8, 0x8e, 0x6f, 0x05, 0xce, 0x6b, 0x6b, 0xc4, 0x3e,
	0x59, 0x8f, 0x36, 0xd6, 0xdb, 0xc8, 0xf9, 0x25, 0x7b, 0xb8, 0xe3, 0x56, 0xb6, 0x2c, 0xc1, 0x04,
	0x2f, 0x5a, 0x83, 0xbd, 0x61, 0x92, 0x1e, 0x6f, 0xec, 0xa3, 0x4a, 0xe0, 0x8f, 0x59, 0xdb, 0x83,
	0x5b, 0x69, 0x05, 0x5e, 0x3c, 0xa0, 0x39, 0x37, 0xef, 0xfc, 0x6b, 0x76, 0x44, 0x9b, 0x57, 0xb6,
	0xd8, 0xac, 0xdb, 0x1e, 0x34, 0x86, 0xdd, 0xb4, 0x5f, 0xf3, 0x7a, 0xd9, 0x21, 0x3b, 0xca, 0xb5,
	0x97, 0x93, 0x02, 0x32, 0x07, 0x85, 0x5c, 0x67, 0xe1, 0x83, 0x48, 0x06, 0x8d, 0x61, 0x3b, 0xed,
	0x55, 0x3c, 0x45, 0x7c, 0xf3, 0x01, 0x27, 0x0d, 0x4e, 0xab, 0x45, 0x01, 0x99, 0x36, 0x01, 0xdc,
	0x4a, 0x16, 0xe2, 0x70, 0xd0, 0x18, 0xee, 0xa5, 0xfd, 0x8a, 0xbf, 0xad, 0x30, 0x4e, 0x2a, 0x8b,
	0xc2, 0xde, 0x67, 0x1e, 0x8a, 0x69, 0xa6, 0xac, 0x31, 0x5e, 0x74, 0xe2, 0xa4, 0xc4, 0xc7, 0x50,
	0x4c, 0x47, 0x48, 0x2f, 0xfe, 0x7e, 0xc0, 0xda, 0xd7, 0x00, 0xee, 0x67, 0xf0, 0x8a, 0x7f, 0xc5,
	0x7a, 0x93, 0x75, 0x00, 0x9f, 0x39, 0x50, 0xa0, 0x57, 0x90, 0x8b, 0xc6, 0xa0, 0x31, 0xdc, 0x4f,
	0xbb, 0x44, 0xd3, 0x0a, 0xf2, 0xcf, 0x18, 0x8b, 0x36, 0x0f, 0x26, 0x88, 0x26, 0x59, 0x12, 0x22,
	0x63, 0x30, 0x81, 0x9f, 0xb3, 0xa4, 0x90, 0x3e, 0xe0, 0x24, 0xab, 0xaa, 0x30, 0x6d, 0x04, 0x29,
	0xa8, 0xd5, 0x46, 0xf4, 0x60, 0xf2, 0xaa, 0x14, 0x24, 0x8e, 0xc1, 0xe4, 0xfc, 0x53, 0x96, 0xe0,
	0x5e, 0x41, 0x05, 0xc8, 0x45, 0x8b, 0xf6, 0xbb, 0x05, 0x9c, 0xb3, 0x7d, 0x99, 0xe7, 0x4e, 0x1c,
	0xd0, 0x28, 0x7a, 0xe6, 0x4f, 0xd8, 0x9e, 0x9a, 0xce, 0xe8, 0xfc, 0x0f, 0xbf, 0xeb, 0x5e, 0x52,
	0x54, 0x2e, 0x63, 0x4c, 0x52, 0x54, 0xb8, 0x60, 0x0f, 0xb4, 0x99, 0xd8, 0x3b, 0x93, 0x53, 0x01,
	0xda, 0x69, 0xfd, 0xca, 0x7b, 0xac, 0x69, 0x24, 0x1d, 0x75, 0x92, 0x36, 0x8d, 0xc4, 0x77, 0x9d,
	0x0b, 0x36, 0x68, 0x0c, 0x5b, 0x69, 0x53, 0xd3, 0x57, 0x6e, 0xf3, 0x40, 0x07, 0x9d, 0xa4, 0xc9,
	0x26, 0x06, 0xff, 0x29, 0x7f, 0xe7, 0x7f, 0xe5, 0xff, 0x92, 0x75, 0xab, 0xaa, 0x67, 0x0b, 0x63,
	0xef, 0x8d, 0xe8, 0xd2, 0xd2, 0x9d, 0x0a, 0xfe, 0x8a, 0x8c, 0x7f, 0xcb, 0x4e, 0x64, 0xbe, 0x02,
	0x17, 0xb4, 0x87, 0x3c, 0xa3, 0x58, 0x60, 0x56, 0x44, 0x8f, 0x72, 0xc2, 0xb7, 0xda, 0x35, 0x4a,
	0xb7, 0xe0, 0x3e, 0x9a, 0xaa, 0xfe, 0xc7, 0x53, 0xf5, 0x03, 0x7b, 0x84, 0x27, 0x9c, 0xcd, 0x41,
	0xe6, 0xe0, 0x7c, 0xb6, 0x74, 0x30, 0x05, 0xe7, 0x20, 0x17, 0x47, 0xb4, 0x95, 0x13, 0x54, 0xdf,
	0x44, 0xf1, 0xba, 0xd6, 0x30, 0x36, 0x2b, 0xfc, 0x62, 0xb5, 0xd8, 0x26, 0xe0, 0x38, 0xc6, 0x66,
	0x05, 0xee, 0x4a, 0x2d, 0x36, 0x11, 0x78, 0xce, 0xfa, 0xf7, 0x3a, 0x18, 0xf0, 0x3e, 0x03, 0x83,
	0x21, 0xcd, 0x05, 0x8f, 0xc6, 0x0a, 0xbf, 0x8e, 0x14, 0x8f, 0xe2, 0x5e, 0x3b, 0xc8, 0xc0, 0x28,
	0x9b, 0x6b, 0x33, 0x13, 0x0f, 0xe9, 0xac, 0x3a, 0x08, 0x5f, 0x57, 0x8c, 0x3f, 0x61, 0x87, 0x41,
	0x97, 0x90, 0xd9, 0xe9, 0xd4, 0x43, 0x10, 0x27, 0x14, 0x6a, 0x86, 0xe8, 0x77, 0x22, 0x18, 0x4c,
	0x32, 0x6c, 0xd3, 0x71, 0x1a, 0x2f, 0x3c, 0xd2, 0xd1, 0x26, 0x21, 0xcf, 0x59, 0xdf, 0x07, 0xe9,
	0x82, 0x36, 0xb3, 0x6c, 0x0e, 0x7a, 0x36, 0x0f, 0xe2, 0x11, 0xd5, 0xb3, 0x57, 0xe3, 0x37, 0x44,
	0xb1, 0xb6, 0x94, 0xc2, 0x49, 0x61, 0xd5, 0x42, 0x9c, 0x91, 0x87, 0x72, 0xf9, 0x0a, 0x01, 0x96,
	0x86, 0x64, 0x69, 0x8c, 0xbd, 0x33, 0x0a, 0xf2, 0xca, 0x28, 0x06, 0x8d, 0x61, 0x27, 0xe5, 0xa8,
	0x5d, 0xd5, 0x52, 0x1c, 0xf1, 0x8c, 0xf5, 0x69, 0xc4, 0x12, 0x97, 0x36, 0xd6, 0x28, 0x10, 0x9f,
	0xc4, 0xab, 0x83, 0xf8, 0x5a, 0x9b, 0xd9, 0x7b, 0x84, 0xfc, 0x29, 0xeb, 0x6d, 0x7d, 0xb8, 0x79,
	0xf1, 0x38, 0x9e, 0x47, 0x6d, 0xbb, 0xd1, 0x25, 0x60, 0x1d, 0xb6, 0xae, 0x52, 0x2b, 0x67, 0xbd,
	0x38, 0xa7, 0x43, 0xe9, 0xd5, 0xbe, 0x77, 0x44, 0x2f, 0xfe, 0xda, 0x67, 0x87, 0x7f, 0xc8, 0xa2,
	0x80, 0x30, 0x0e, 0x32, 0x78, 0xfe, 0x23, 0x3b, 0x2b, 0x25, 0x76, 0x07, 0x23, 0x8d, 0xc2, 0x3e,
	0x81, 0xc1, 0x9a, 0x39, 0xf0, 0x9e, 0xae, 0x72, 0x3b, 0x3d, 0xdd, 0x91, 0xdf, 0x9a, 0xeb, 0x4a,
	0xc4, 0x68, 0xed, 0x8e, 0xa3, 0x9e, 0xda, 0xa4, 0x9d, 0xf5, 0x77, 0x38, 0x75, 0xd5, 0x17, 0x8c,
	0xef, 0x5a, 0xd5, 0x5a, 0x15, 0xe0, 0xe9, 0x9e, 0xb7, 0xd2, 0xe3, 0x1d, 0x65, 0x44, 0x02, 0x1f,
	0xb1, 0xcf, 0x77, 0xed, 0xdb, 0x63, 0xcf, 0x56, 0xda, 0x6b, 0x2c, 0xe5, 0x3e, 0x0d, 0x3d, 0xdf,
	0x71, 0xfd, 0x56, 0x57, 0xe2, 0x36, 0x5a, 0xf8, 0x4f, 0x4c, 0x54, 0x01, 0x89, 0x13, 0xec, 0x78,
	0xa9, 0x4f, 0x24, 0xe9, 0x69, 0x4c, 0x0b, 0x8e, 0x7c, 0xb7, 0x15, 0xf1, 0xfa, 0xfb, 0xb5, 0x51,
	0x18, 0xbc, 0x83, 0x78, 0xfd, 0xab, 0x57, 0xfe, 0x05, 0xeb, 0xe0, 0x63, 0x46, 0xc9, 0x80, 0xbc,
	0x6a, 0xe1, 0x87, 0xc8, 0xc6, 0x11, 0xd1, 0x25, 0x42, 0x8b, 0x03, 0x5c, 0x0f, 0x6b, 0xe1, 0x41,
	0x59, 0x93, 0x7b, 0x6a, 0x25, 0x7b, 0xe9, 0x09, 0xaa, 0x69, 0x2d, 0x8e, 0xa3, 0x86, 0xff, 0x3a,
	0x34, 0x4a, 0xdd, 0x39, 0x87, 0xff, 0x24, 0x31, 0x3a, 0x09, 0x7d, 0xe4, 0x11, 0x2a, 0xa3, 0x28,
	0xc4, 0xe0, 0x9c, 0xb3, 0x84, 0xdc, 0x53, 0x67, 0xcb, 0xaa, 0xf9, 0xb4, 0x11, 0xfc, 0xe2, 0x6c,
	0xc9, 0xcf, 0xe2, 0xee, 0xb3, 0x60, 0xa9, 0xff, 0xb4, 0xd2, 0x03, 0x7c, 0xbd, 0xb1, 0xd4, 0xa8,
	0xb5, 0x0b, 0xf3, 0x5c, 0xae, 0xab, 0xf9, 0x3b, 0xa4, 0x77, 0x6b, 0x4a, 0x93, 0xbf, 0x7a, 0xfa,
	0xe7, 0xc5, 0x4c, 0x87, 0xf9, 0xdd, 0xe4, 0x52, 0xd9, 0xf2, 0xe5, 0x72, 0x11, 0x5e, 0x28, 0xe9,
	0xe7, 0xf8, 0x90, 0xbf, 0x2c, 0x0c, 0xfe, 0xdc, 0x52, 0x4d, 0x0e, 0xa8, 0x79, 0x7c, 0xff, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0xa6, 0xd0, 0xf8, 0x74, 0x07, 0x00, 0x00,
}
