// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkt.proto

package lnrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NeutrinoBan struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	EndTime              string   `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeutrinoBan) Reset()         { *m = NeutrinoBan{} }
func (m *NeutrinoBan) String() string { return proto.CompactTextString(m) }
func (*NeutrinoBan) ProtoMessage()    {}
func (*NeutrinoBan) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{0}
}

func (m *NeutrinoBan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeutrinoBan.Unmarshal(m, b)
}
func (m *NeutrinoBan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeutrinoBan.Marshal(b, m, deterministic)
}
func (m *NeutrinoBan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeutrinoBan.Merge(m, src)
}
func (m *NeutrinoBan) XXX_Size() int {
	return xxx_messageInfo_NeutrinoBan.Size(m)
}
func (m *NeutrinoBan) XXX_DiscardUnknown() {
	xxx_messageInfo_NeutrinoBan.DiscardUnknown(m)
}

var xxx_messageInfo_NeutrinoBan proto.InternalMessageInfo

func (m *NeutrinoBan) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *NeutrinoBan) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *NeutrinoBan) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type NeutrinoQuery struct {
	Peer                 string   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	ReqNum               uint32   `protobuf:"varint,3,opt,name=req_num,json=reqNum,proto3" json:"req_num,omitempty"`
	CreateTime           uint32   `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	LastRequestTime      uint32   `protobuf:"varint,5,opt,name=last_request_time,json=lastRequestTime,proto3" json:"last_request_time,omitempty"`
	LastResponseTime     uint32   `protobuf:"varint,6,opt,name=last_response_time,json=lastResponseTime,proto3" json:"last_response_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NeutrinoQuery) Reset()         { *m = NeutrinoQuery{} }
func (m *NeutrinoQuery) String() string { return proto.CompactTextString(m) }
func (*NeutrinoQuery) ProtoMessage()    {}
func (*NeutrinoQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{1}
}

func (m *NeutrinoQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeutrinoQuery.Unmarshal(m, b)
}
func (m *NeutrinoQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeutrinoQuery.Marshal(b, m, deterministic)
}
func (m *NeutrinoQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeutrinoQuery.Merge(m, src)
}
func (m *NeutrinoQuery) XXX_Size() int {
	return xxx_messageInfo_NeutrinoQuery.Size(m)
}
func (m *NeutrinoQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_NeutrinoQuery.DiscardUnknown(m)
}

var xxx_messageInfo_NeutrinoQuery proto.InternalMessageInfo

func (m *NeutrinoQuery) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *NeutrinoQuery) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *NeutrinoQuery) GetReqNum() uint32 {
	if m != nil {
		return m.ReqNum
	}
	return 0
}

func (m *NeutrinoQuery) GetCreateTime() uint32 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *NeutrinoQuery) GetLastRequestTime() uint32 {
	if m != nil {
		return m.LastRequestTime
	}
	return 0
}

func (m *NeutrinoQuery) GetLastResponseTime() uint32 {
	if m != nil {
		return m.LastResponseTime
	}
	return 0
}

type NeutrinoInfo struct {
	Peers                []*PeerDesc      `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Bans                 []*NeutrinoBan   `protobuf:"bytes,2,rep,name=bans,proto3" json:"bans,omitempty"`
	Queries              []*NeutrinoQuery `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	BlockHash            string           `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Height               int32            `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	BlockTimestamp       string           `protobuf:"bytes,6,opt,name=block_timestamp,json=blockTimestamp,proto3" json:"block_timestamp,omitempty"`
	IsSyncing            bool             `protobuf:"varint,7,opt,name=is_syncing,json=isSyncing,proto3" json:"is_syncing,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *NeutrinoInfo) Reset()         { *m = NeutrinoInfo{} }
func (m *NeutrinoInfo) String() string { return proto.CompactTextString(m) }
func (*NeutrinoInfo) ProtoMessage()    {}
func (*NeutrinoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{2}
}

func (m *NeutrinoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NeutrinoInfo.Unmarshal(m, b)
}
func (m *NeutrinoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NeutrinoInfo.Marshal(b, m, deterministic)
}
func (m *NeutrinoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NeutrinoInfo.Merge(m, src)
}
func (m *NeutrinoInfo) XXX_Size() int {
	return xxx_messageInfo_NeutrinoInfo.Size(m)
}
func (m *NeutrinoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NeutrinoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NeutrinoInfo proto.InternalMessageInfo

func (m *NeutrinoInfo) GetPeers() []*PeerDesc {
	if m != nil {
		return m.Peers
	}
	return nil
}

func (m *NeutrinoInfo) GetBans() []*NeutrinoBan {
	if m != nil {
		return m.Bans
	}
	return nil
}

func (m *NeutrinoInfo) GetQueries() []*NeutrinoQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *NeutrinoInfo) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *NeutrinoInfo) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *NeutrinoInfo) GetBlockTimestamp() string {
	if m != nil {
		return m.BlockTimestamp
	}
	return ""
}

func (m *NeutrinoInfo) GetIsSyncing() bool {
	if m != nil {
		return m.IsSyncing
	}
	return false
}

type WalletInfo struct {
	CurrentBlockHash      string       `protobuf:"bytes,1,opt,name=current_block_hash,json=currentBlockHash,proto3" json:"current_block_hash,omitempty"`
	CurrentHeight         int32        `protobuf:"varint,2,opt,name=current_height,json=currentHeight,proto3" json:"current_height,omitempty"`
	CurrentBlockTimestamp string       `protobuf:"bytes,3,opt,name=current_block_timestamp,json=currentBlockTimestamp,proto3" json:"current_block_timestamp,omitempty"`
	WalletVersion         int32        `protobuf:"varint,4,opt,name=wallet_version,json=walletVersion,proto3" json:"wallet_version,omitempty"`
	WalletStats           *WalletStats `protobuf:"bytes,5,opt,name=wallet_stats,json=walletStats,proto3" json:"wallet_stats,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}     `json:"-"`
	XXX_unrecognized      []byte       `json:"-"`
	XXX_sizecache         int32        `json:"-"`
}

func (m *WalletInfo) Reset()         { *m = WalletInfo{} }
func (m *WalletInfo) String() string { return proto.CompactTextString(m) }
func (*WalletInfo) ProtoMessage()    {}
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{3}
}

func (m *WalletInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletInfo.Unmarshal(m, b)
}
func (m *WalletInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletInfo.Marshal(b, m, deterministic)
}
func (m *WalletInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletInfo.Merge(m, src)
}
func (m *WalletInfo) XXX_Size() int {
	return xxx_messageInfo_WalletInfo.Size(m)
}
func (m *WalletInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WalletInfo proto.InternalMessageInfo

func (m *WalletInfo) GetCurrentBlockHash() string {
	if m != nil {
		return m.CurrentBlockHash
	}
	return ""
}

func (m *WalletInfo) GetCurrentHeight() int32 {
	if m != nil {
		return m.CurrentHeight
	}
	return 0
}

func (m *WalletInfo) GetCurrentBlockTimestamp() string {
	if m != nil {
		return m.CurrentBlockTimestamp
	}
	return ""
}

func (m *WalletInfo) GetWalletVersion() int32 {
	if m != nil {
		return m.WalletVersion
	}
	return 0
}

func (m *WalletInfo) GetWalletStats() *WalletStats {
	if m != nil {
		return m.WalletStats
	}
	return nil
}

type PeerDesc struct {
	BytesReceived        uint64   `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BytesSent            uint64   `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	LastRecv             string   `protobuf:"bytes,3,opt,name=last_recv,json=lastRecv,proto3" json:"last_recv,omitempty"`
	LastSend             string   `protobuf:"bytes,4,opt,name=last_send,json=lastSend,proto3" json:"last_send,omitempty"`
	Connected            bool     `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	Addr                 string   `protobuf:"bytes,6,opt,name=addr,proto3" json:"addr,omitempty"`
	Inbound              bool     `protobuf:"varint,7,opt,name=inbound,proto3" json:"inbound,omitempty"`
	Na                   string   `protobuf:"bytes,8,opt,name=na,proto3" json:"na,omitempty"`
	Id                   int32    `protobuf:"varint,9,opt,name=id,proto3" json:"id,omitempty"`
	UserAgent            string   `protobuf:"bytes,10,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Services             string   `protobuf:"bytes,11,opt,name=services,proto3" json:"services,omitempty"`
	VersionKnown         bool     `protobuf:"varint,12,opt,name=version_known,json=versionKnown,proto3" json:"version_known,omitempty"`
	AdvertisedProtoVer   uint32   `protobuf:"varint,13,opt,name=advertised_proto_ver,json=advertisedProtoVer,proto3" json:"advertised_proto_ver,omitempty"`
	ProtocolVersion      uint32   `protobuf:"varint,14,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SendHeadersPreferred bool     `protobuf:"varint,15,opt,name=send_headers_preferred,json=sendHeadersPreferred,proto3" json:"send_headers_preferred,omitempty"`
	VerAckReceived       bool     `protobuf:"varint,16,opt,name=ver_ack_received,json=verAckReceived,proto3" json:"ver_ack_received,omitempty"`
	WitnessEnabled       bool     `protobuf:"varint,17,opt,name=witness_enabled,json=witnessEnabled,proto3" json:"witness_enabled,omitempty"`
	WireEncoding         string   `protobuf:"bytes,18,opt,name=wire_encoding,json=wireEncoding,proto3" json:"wire_encoding,omitempty"`
	TimeOffset           int64    `protobuf:"varint,19,opt,name=time_offset,json=timeOffset,proto3" json:"time_offset,omitempty"`
	TimeConnected        string   `protobuf:"bytes,20,opt,name=time_connected,json=timeConnected,proto3" json:"time_connected,omitempty"`
	StartingHeight       int32    `protobuf:"varint,21,opt,name=starting_height,json=startingHeight,proto3" json:"starting_height,omitempty"`
	LastBlock            int32    `protobuf:"varint,22,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	LastAnnouncedBlock   []byte   `protobuf:"bytes,23,opt,name=last_announced_block,json=lastAnnouncedBlock,proto3" json:"last_announced_block,omitempty"`
	LastPingNonce        uint64   `protobuf:"varint,24,opt,name=last_ping_nonce,json=lastPingNonce,proto3" json:"last_ping_nonce,omitempty"`
	LastPingTime         string   `protobuf:"bytes,25,opt,name=last_ping_time,json=lastPingTime,proto3" json:"last_ping_time,omitempty"`
	LastPingMicros       int64    `protobuf:"varint,26,opt,name=last_ping_micros,json=lastPingMicros,proto3" json:"last_ping_micros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerDesc) Reset()         { *m = PeerDesc{} }
func (m *PeerDesc) String() string { return proto.CompactTextString(m) }
func (*PeerDesc) ProtoMessage()    {}
func (*PeerDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{4}
}

func (m *PeerDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDesc.Unmarshal(m, b)
}
func (m *PeerDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDesc.Marshal(b, m, deterministic)
}
func (m *PeerDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDesc.Merge(m, src)
}
func (m *PeerDesc) XXX_Size() int {
	return xxx_messageInfo_PeerDesc.Size(m)
}
func (m *PeerDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDesc.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDesc proto.InternalMessageInfo

func (m *PeerDesc) GetBytesReceived() uint64 {
	if m != nil {
		return m.BytesReceived
	}
	return 0
}

func (m *PeerDesc) GetBytesSent() uint64 {
	if m != nil {
		return m.BytesSent
	}
	return 0
}

func (m *PeerDesc) GetLastRecv() string {
	if m != nil {
		return m.LastRecv
	}
	return ""
}

func (m *PeerDesc) GetLastSend() string {
	if m != nil {
		return m.LastSend
	}
	return ""
}

func (m *PeerDesc) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

func (m *PeerDesc) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PeerDesc) GetInbound() bool {
	if m != nil {
		return m.Inbound
	}
	return false
}

func (m *PeerDesc) GetNa() string {
	if m != nil {
		return m.Na
	}
	return ""
}

func (m *PeerDesc) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PeerDesc) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *PeerDesc) GetServices() string {
	if m != nil {
		return m.Services
	}
	return ""
}

func (m *PeerDesc) GetVersionKnown() bool {
	if m != nil {
		return m.VersionKnown
	}
	return false
}

func (m *PeerDesc) GetAdvertisedProtoVer() uint32 {
	if m != nil {
		return m.AdvertisedProtoVer
	}
	return 0
}

func (m *PeerDesc) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *PeerDesc) GetSendHeadersPreferred() bool {
	if m != nil {
		return m.SendHeadersPreferred
	}
	return false
}

func (m *PeerDesc) GetVerAckReceived() bool {
	if m != nil {
		return m.VerAckReceived
	}
	return false
}

func (m *PeerDesc) GetWitnessEnabled() bool {
	if m != nil {
		return m.WitnessEnabled
	}
	return false
}

func (m *PeerDesc) GetWireEncoding() string {
	if m != nil {
		return m.WireEncoding
	}
	return ""
}

func (m *PeerDesc) GetTimeOffset() int64 {
	if m != nil {
		return m.TimeOffset
	}
	return 0
}

func (m *PeerDesc) GetTimeConnected() string {
	if m != nil {
		return m.TimeConnected
	}
	return ""
}

func (m *PeerDesc) GetStartingHeight() int32 {
	if m != nil {
		return m.StartingHeight
	}
	return 0
}

func (m *PeerDesc) GetLastBlock() int32 {
	if m != nil {
		return m.LastBlock
	}
	return 0
}

func (m *PeerDesc) GetLastAnnouncedBlock() []byte {
	if m != nil {
		return m.LastAnnouncedBlock
	}
	return nil
}

func (m *PeerDesc) GetLastPingNonce() uint64 {
	if m != nil {
		return m.LastPingNonce
	}
	return 0
}

func (m *PeerDesc) GetLastPingTime() string {
	if m != nil {
		return m.LastPingTime
	}
	return ""
}

func (m *PeerDesc) GetLastPingMicros() int64 {
	if m != nil {
		return m.LastPingMicros
	}
	return 0
}

type WalletStats struct {
	MaintenanceInProgress       bool     `protobuf:"varint,1,opt,name=maintenance_in_progress,json=maintenanceInProgress,proto3" json:"maintenance_in_progress,omitempty"`
	MaintenanceName             string   `protobuf:"bytes,2,opt,name=maintenance_name,json=maintenanceName,proto3" json:"maintenance_name,omitempty"`
	MaintenanceCycles           int32    `protobuf:"varint,3,opt,name=maintenance_cycles,json=maintenanceCycles,proto3" json:"maintenance_cycles,omitempty"`
	MaintenanceLastBlockVisited int32    `protobuf:"varint,4,opt,name=maintenance_last_block_visited,json=maintenanceLastBlockVisited,proto3" json:"maintenance_last_block_visited,omitempty"`
	TimeOfLastMaintenance       string   `protobuf:"bytes,5,opt,name=time_of_last_maintenance,json=timeOfLastMaintenance,proto3" json:"time_of_last_maintenance,omitempty"`
	Syncing                     bool     `protobuf:"varint,6,opt,name=syncing,proto3" json:"syncing,omitempty"`
	SyncStarted                 string   `protobuf:"bytes,7,opt,name=sync_started,json=syncStarted,proto3" json:"sync_started,omitempty"`
	SyncRemainingSeconds        int64    `protobuf:"varint,8,opt,name=sync_remaining_seconds,json=syncRemainingSeconds,proto3" json:"sync_remaining_seconds,omitempty"`
	SyncCurrentBlock            int32    `protobuf:"varint,9,opt,name=sync_current_block,json=syncCurrentBlock,proto3" json:"sync_current_block,omitempty"`
	SyncFrom                    int32    `protobuf:"varint,10,opt,name=sync_from,json=syncFrom,proto3" json:"sync_from,omitempty"`
	SyncTo                      int32    `protobuf:"varint,11,opt,name=sync_to,json=syncTo,proto3" json:"sync_to,omitempty"`
	BirthdayBlock               int32    `protobuf:"varint,12,opt,name=birthday_block,json=birthdayBlock,proto3" json:"birthday_block,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *WalletStats) Reset()         { *m = WalletStats{} }
func (m *WalletStats) String() string { return proto.CompactTextString(m) }
func (*WalletStats) ProtoMessage()    {}
func (*WalletStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{5}
}

func (m *WalletStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletStats.Unmarshal(m, b)
}
func (m *WalletStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletStats.Marshal(b, m, deterministic)
}
func (m *WalletStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletStats.Merge(m, src)
}
func (m *WalletStats) XXX_Size() int {
	return xxx_messageInfo_WalletStats.Size(m)
}
func (m *WalletStats) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletStats.DiscardUnknown(m)
}

var xxx_messageInfo_WalletStats proto.InternalMessageInfo

func (m *WalletStats) GetMaintenanceInProgress() bool {
	if m != nil {
		return m.MaintenanceInProgress
	}
	return false
}

func (m *WalletStats) GetMaintenanceName() string {
	if m != nil {
		return m.MaintenanceName
	}
	return ""
}

func (m *WalletStats) GetMaintenanceCycles() int32 {
	if m != nil {
		return m.MaintenanceCycles
	}
	return 0
}

func (m *WalletStats) GetMaintenanceLastBlockVisited() int32 {
	if m != nil {
		return m.MaintenanceLastBlockVisited
	}
	return 0
}

func (m *WalletStats) GetTimeOfLastMaintenance() string {
	if m != nil {
		return m.TimeOfLastMaintenance
	}
	return ""
}

func (m *WalletStats) GetSyncing() bool {
	if m != nil {
		return m.Syncing
	}
	return false
}

func (m *WalletStats) GetSyncStarted() string {
	if m != nil {
		return m.SyncStarted
	}
	return ""
}

func (m *WalletStats) GetSyncRemainingSeconds() int64 {
	if m != nil {
		return m.SyncRemainingSeconds
	}
	return 0
}

func (m *WalletStats) GetSyncCurrentBlock() int32 {
	if m != nil {
		return m.SyncCurrentBlock
	}
	return 0
}

func (m *WalletStats) GetSyncFrom() int32 {
	if m != nil {
		return m.SyncFrom
	}
	return 0
}

func (m *WalletStats) GetSyncTo() int32 {
	if m != nil {
		return m.SyncTo
	}
	return 0
}

func (m *WalletStats) GetBirthdayBlock() int32 {
	if m != nil {
		return m.BirthdayBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*NeutrinoBan)(nil), "lnrpc.NeutrinoBan")
	proto.RegisterType((*NeutrinoQuery)(nil), "lnrpc.NeutrinoQuery")
	proto.RegisterType((*NeutrinoInfo)(nil), "lnrpc.NeutrinoInfo")
	proto.RegisterType((*WalletInfo)(nil), "lnrpc.WalletInfo")
	proto.RegisterType((*PeerDesc)(nil), "lnrpc.PeerDesc")
	proto.RegisterType((*WalletStats)(nil), "lnrpc.WalletStats")
}

func init() { proto.RegisterFile("pkt.proto", fileDescriptor_3c5f63a845a51abc) }

var fileDescriptor_3c5f63a845a51abc = []byte{
	// 1162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x56, 0xdb, 0x6e, 0x1b, 0xb7,
	0x16, 0x85, 0x64, 0xcb, 0x92, 0xb6, 0xae, 0xe1, 0xb1, 0x93, 0x49, 0x72, 0x72, 0x8e, 0xeb, 0xe6,
	0xa2, 0x16, 0x89, 0x53, 0xf4, 0xfa, 0x9c, 0xb8, 0x29, 0x12, 0xb4, 0x71, 0xdd, 0xb1, 0x91, 0x02,
	0x7d, 0x19, 0x50, 0x9c, 0x6d, 0x89, 0xb0, 0x86, 0x23, 0x93, 0x94, 0x0c, 0xff, 0x43, 0xff, 0x20,
	0x5f, 0xd5, 0xaf, 0xe9, 0x6b, 0xb1, 0x37, 0x39, 0xd2, 0xa4, 0x0f, 0x06, 0x86, 0x6b, 0xad, 0xd9,
	0xc3, 0x7d, 0x5b, 0x32, 0x74, 0x97, 0x57, 0xfe, 0x78, 0x69, 0x4b, 0x5f, 0x8a, 0xd6, 0xc2, 0xd8,
	0xa5, 0x3a, 0xba, 0x80, 0xde, 0x29, 0xae, 0xbc, 0xd5, 0xa6, 0x7c, 0x2d, 0x8d, 0x10, 0xb0, 0x2b,
	0xf3, 0xdc, 0x26, 0x8d, 0xc3, 0xc6, 0xa4, 0x9b, 0xf2, 0xb3, 0xb8, 0x0b, 0x7b, 0x16, 0xa5, 0x2b,
	0x4d, 0xd2, 0x64, 0x34, 0x9e, 0xc4, 0x7d, 0xe8, 0xa0, 0xc9, 0x33, 0xaf, 0x0b, 0x4c, 0x76, 0x98,
	0x69, 0xa3, 0xc9, 0x2f, 0x74, 0x81, 0x47, 0x7f, 0x35, 0x60, 0x50, 0x85, 0xfd, 0x6d, 0x85, 0xf6,
	0x96, 0x02, 0x2f, 0x11, 0x37, 0x81, 0xe9, 0x59, 0x24, 0xd0, 0x56, 0x65, 0x51, 0x48, 0x93, 0xc7,
	0xc8, 0xd5, 0x51, 0xdc, 0x83, 0xb6, 0xc5, 0xeb, 0xcc, 0xac, 0x0a, 0x8e, 0x3c, 0xa0, 0x6f, 0x5e,
	0x9f, 0xae, 0x0a, 0xf1, 0x7f, 0xe8, 0x29, 0x8b, 0xd2, 0x63, 0xf8, 0xec, 0x2e, 0x93, 0x10, 0x20,
	0xfa, 0xb2, 0xf8, 0x12, 0xee, 0x2c, 0xa4, 0xf3, 0x99, 0xc5, 0xeb, 0x15, 0x3a, 0x1f, 0x64, 0x2d,
	0x96, 0x8d, 0x88, 0x48, 0x03, 0xce, 0xda, 0xe7, 0x20, 0xa2, 0xd6, 0x2d, 0x4b, 0xe3, 0x62, 0xcc,
	0x3d, 0x16, 0x8f, 0x83, 0x38, 0x10, 0x9c, 0xd3, 0x9f, 0x4d, 0xe8, 0x57, 0x39, 0xbd, 0x33, 0x97,
	0xa5, 0x78, 0x02, 0x2d, 0x4a, 0xc3, 0x25, 0x8d, 0xc3, 0x9d, 0x49, 0xef, 0xeb, 0xd1, 0x31, 0x57,
	0xf4, 0xf8, 0x0c, 0xd1, 0xfe, 0x88, 0x4e, 0xa5, 0x81, 0x15, 0x4f, 0x61, 0x77, 0x2a, 0x8d, 0x4b,
	0x9a, 0xac, 0x12, 0x51, 0x55, 0x2b, 0x7a, 0xca, 0xbc, 0x38, 0x86, 0xf6, 0xf5, 0x0a, 0xad, 0x46,
	0x97, 0xec, 0xb0, 0x74, 0xff, 0x5f, 0x52, 0x2e, 0x64, 0x5a, 0x89, 0xc4, 0x23, 0x80, 0xe9, 0xa2,
	0x54, 0x57, 0xd9, 0x5c, 0xba, 0x39, 0x57, 0xa2, 0x9b, 0x76, 0x19, 0x79, 0x2b, 0xdd, 0x9c, 0xba,
	0x36, 0x47, 0x3d, 0x9b, 0x7b, 0xce, 0xbe, 0x95, 0xc6, 0x93, 0x78, 0x06, 0xa3, 0xf0, 0x1a, 0x25,
	0xeb, 0xbc, 0x2c, 0x96, 0x9c, 0x71, 0x37, 0x1d, 0x32, 0x7c, 0x51, 0xa1, 0x14, 0x5f, 0xbb, 0xcc,
	0xdd, 0x1a, 0xa5, 0xcd, 0x2c, 0x69, 0x1f, 0x36, 0x26, 0x9d, 0xb4, 0xab, 0xdd, 0x79, 0x00, 0x8e,
	0xfe, 0x6e, 0x00, 0xfc, 0x2e, 0x17, 0x0b, 0xf4, 0x5c, 0x8c, 0xe7, 0x20, 0xd4, 0xca, 0x5a, 0x34,
	0x3e, 0xab, 0xdd, 0x2a, 0x74, 0x7b, 0x1c, 0x99, 0xd7, 0x9b, 0xcb, 0x3d, 0x81, 0x61, 0xa5, 0x8e,
	0x97, 0x6c, 0xf2, 0x25, 0x07, 0x11, 0x7d, 0x1b, 0xee, 0xfa, 0x3d, 0xdc, 0xfb, 0x34, 0xe8, 0xf6,
	0xce, 0x61, 0xe0, 0x0e, 0xea, 0x91, 0xb7, 0x57, 0x7f, 0x02, 0xc3, 0x1b, 0xbe, 0x5a, 0xb6, 0x46,
	0xeb, 0x74, 0x69, 0xb8, 0x3c, 0xad, 0x74, 0x10, 0xd0, 0x0f, 0x01, 0x14, 0xdf, 0x41, 0x3f, 0xca,
	0x9c, 0x97, 0xde, 0x71, 0xa1, 0xb6, 0x1d, 0x0a, 0xc9, 0x9d, 0x13, 0x93, 0xf6, 0x6e, 0xb6, 0x87,
	0xa3, 0x8f, 0x6d, 0xe8, 0x54, 0x4d, 0xa6, 0x4f, 0x4d, 0x6f, 0x3d, 0xba, 0xcc, 0xa2, 0x42, 0xbd,
	0xc6, 0x9c, 0x73, 0xde, 0x4d, 0x07, 0x8c, 0xa6, 0x11, 0xe4, 0x66, 0xb1, 0xcc, 0xa1, 0x09, 0xc9,
	0xee, 0xa6, 0x5d, 0x46, 0xce, 0xd1, 0x78, 0xf1, 0x10, 0xba, 0x71, 0x12, 0xd5, 0x3a, 0xa6, 0xd6,
	0x09, 0x03, 0xa8, 0xd6, 0x1b, 0xd2, 0xa1, 0xc9, 0x63, 0x9f, 0x99, 0x3c, 0x47, 0x93, 0x8b, 0xff,
	0x42, 0x57, 0x95, 0xc6, 0xa0, 0xf2, 0x98, 0x73, 0x02, 0x9d, 0x74, 0x0b, 0x6c, 0xd6, 0x79, 0xaf,
	0xb6, 0xce, 0x09, 0xb4, 0xb5, 0x99, 0x96, 0x2b, 0x93, 0xc7, 0xa6, 0x56, 0x47, 0x31, 0x84, 0xa6,
	0x91, 0x49, 0x87, 0xb5, 0x4d, 0x23, 0xe9, 0xac, 0xf3, 0xa4, 0xcb, 0xa5, 0x6b, 0x6a, 0x4e, 0x62,
	0xe5, 0xd0, 0x66, 0x72, 0x46, 0x49, 0x40, 0x98, 0x38, 0x42, 0x5e, 0x11, 0x20, 0x1e, 0x40, 0xc7,
	0xa1, 0x5d, 0x6b, 0x85, 0x2e, 0xe9, 0x85, 0x6b, 0x56, 0x67, 0xf1, 0x39, 0x0c, 0x62, 0x2b, 0xb2,
	0x2b, 0x53, 0xde, 0x98, 0xa4, 0xcf, 0x9f, 0xee, 0x47, 0xf0, 0x67, 0xc2, 0xc4, 0x57, 0xb0, 0x2f,
	0xf3, 0x35, 0x5a, 0xaf, 0x1d, 0xe6, 0x19, 0xdb, 0x14, 0x35, 0x30, 0x19, 0xf0, 0x46, 0x8a, 0x2d,
	0x77, 0x46, 0xd4, 0x07, 0xb4, 0xe2, 0x0b, 0x18, 0xb3, 0x4c, 0x95, 0x8b, 0x4d, 0xab, 0x87, 0x61,
	0xd9, 0x2b, 0xbc, 0x6a, 0xf6, 0xb7, 0x70, 0x97, 0x0a, 0x98, 0xcd, 0x51, 0xe6, 0x68, 0x5d, 0xb6,
	0xb4, 0x78, 0x89, 0xd6, 0x62, 0x9e, 0x8c, 0xf8, 0x2a, 0xfb, 0xc4, 0xbe, 0x0d, 0xe4, 0x59, 0xc5,
	0x89, 0x09, 0x8c, 0xd7, 0x94, 0xb1, 0xba, 0xda, 0x36, 0x78, 0xcc, 0xfa, 0xe1, 0x1a, 0xed, 0x2b,
	0x75, 0xb5, 0xe9, 0xf0, 0x33, 0x18, 0xdd, 0x68, 0x6f, 0xd0, 0xb9, 0x0c, 0x8d, 0x9c, 0x2e, 0x30,
	0x4f, 0xee, 0x04, 0x61, 0x84, 0xdf, 0x04, 0x94, 0x4a, 0x71, 0xa3, 0x2d, 0x66, 0x68, 0x54, 0x99,
	0xd3, 0x6a, 0x09, 0xae, 0x55, 0x9f, 0xc0, 0x37, 0x11, 0x23, 0x9f, 0xa3, 0x59, 0xcf, 0xca, 0xcb,
	0x4b, 0x87, 0x3e, 0xf9, 0xcf, 0x61, 0x63, 0xb2, 0x93, 0x02, 0x41, 0xbf, 0x32, 0x42, 0x73, 0xc7,
	0x82, 0x6d, 0xf3, 0xf7, 0x39, 0xcc, 0x80, 0xd0, 0x93, 0xcd, 0x00, 0x3c, 0x83, 0x91, 0xf3, 0xd2,
	0x7a, 0x6d, 0x66, 0xd5, 0xa6, 0x1d, 0x70, 0x3f, 0x87, 0x15, 0x1c, 0x57, 0xed, 0x11, 0x00, 0x0f,
	0x19, 0xef, 0x59, 0x72, 0x97, 0x35, 0x3c, 0x76, 0xbc, 0x5a, 0xd4, 0x1a, 0xa6, 0xa5, 0x31, 0xe5,
	0xca, 0x28, 0xcc, 0xa3, 0xf0, 0xde, 0x61, 0x63, 0xd2, 0x4f, 0xd9, 0x46, 0x5f, 0x55, 0x54, 0x78,
	0xe3, 0x29, 0xb0, 0xdf, 0x66, 0x4b, 0xfa, 0xb4, 0x29, 0x8d, 0xc2, 0x24, 0x09, 0x9b, 0x41, 0xf0,
	0x99, 0x36, 0xb3, 0x53, 0x02, 0xc5, 0x63, 0x18, 0x6e, 0x75, 0x6c, 0xc0, 0xf7, 0x43, 0x3d, 0x2a,
	0x19, 0x5b, 0xf5, 0x04, 0xc6, 0x5b, 0x55, 0xa1, 0x95, 0x2d, 0x5d, 0xf2, 0x80, 0x8b, 0x32, 0xac,
	0x74, 0xef, 0x19, 0x3d, 0xfa, 0xb8, 0x0b, 0xbd, 0xda, 0xea, 0x92, 0x87, 0x14, 0x52, 0x1b, 0x8f,
	0x46, 0x1a, 0x85, 0x99, 0x36, 0x34, 0x58, 0x33, 0x8b, 0xce, 0xf1, 0xa6, 0x76, 0xd2, 0x83, 0x1a,
	0xfd, 0xce, 0x9c, 0x45, 0x92, 0x46, 0xab, 0xfe, 0x9e, 0x91, 0x05, 0xc6, 0x5f, 0xa9, 0x51, 0x0d,
	0x3f, 0x95, 0x05, 0x8a, 0x17, 0x20, 0xea, 0x52, 0x75, 0xab, 0x16, 0x6c, 0xe2, 0x54, 0xc3, 0x3b,
	0x35, 0xe6, 0x84, 0x09, 0x71, 0x02, 0xff, 0xab, 0xcb, 0xb7, 0x65, 0xcf, 0xd6, 0xda, 0x69, 0x6a,
	0x65, 0x70, 0xab, 0x87, 0x35, 0xd5, 0x2f, 0x55, 0x27, 0x3e, 0x04, 0x89, 0xf8, 0x01, 0x92, 0x38,
	0x20, 0x21, 0x40, 0x4d, 0xcb, 0x36, 0xd0, 0x4d, 0x0f, 0xc2, 0xb4, 0xd0, 0x9b, 0xef, 0xb7, 0x24,
	0xad, 0x7f, 0xe5, 0xe9, 0x7b, 0x61, 0xfd, 0xe3, 0x51, 0x7c, 0x06, 0x7d, 0x7a, 0xcc, 0x78, 0x32,
	0x30, 0xb8, 0x43, 0x37, 0xed, 0x11, 0x76, 0x1e, 0x20, 0x5e, 0x22, 0x92, 0x58, 0xa4, 0xef, 0x51,
	0x2f, 0x1c, 0xaa, 0xd2, 0xe4, 0x8e, 0x5d, 0x63, 0x27, 0xdd, 0x27, 0x36, 0xad, 0xc8, 0xf3, 0xc0,
	0xd1, 0x6f, 0x03, 0xbf, 0xf5, 0x89, 0x97, 0x47, 0x5f, 0x19, 0x13, 0x73, 0x52, 0x73, 0x71, 0xb2,
	0x3b, 0x56, 0x5f, 0xda, 0xb2, 0x60, 0x93, 0x69, 0xa5, 0x1d, 0x02, 0x7e, 0xb2, 0x65, 0x41, 0xff,
	0x18, 0x30, 0xe9, 0x4b, 0xb6, 0x98, 0x56, 0xba, 0x47, 0xc7, 0x8b, 0x92, 0x7d, 0x58, 0x5b, 0x3f,
	0xcf, 0xe5, 0x6d, 0x8c, 0xdf, 0x0f, 0x96, 0x5f, 0xa1, 0x1c, 0xfc, 0xf5, 0xe3, 0x3f, 0x8e, 0x66,
	0xda, 0xcf, 0x57, 0xd3, 0x63, 0x55, 0x16, 0x2f, 0x97, 0x57, 0xfe, 0x85, 0x92, 0x6e, 0x4e, 0x0f,
	0xf9, 0xcb, 0x85, 0xa1, 0x3f, 0xbb, 0x54, 0xd3, 0x3d, 0x36, 0x8f, 0x6f, 0xfe, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xad, 0x58, 0x54, 0xb5, 0x2f, 0x09, 0x00, 0x00,
}
