// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkt.proto

package lnrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HashFunc struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashFunc) Reset()         { *m = HashFunc{} }
func (m *HashFunc) String() string { return proto.CompactTextString(m) }
func (*HashFunc) ProtoMessage()    {}
func (*HashFunc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{0}
}

func (m *HashFunc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashFunc.Unmarshal(m, b)
}
func (m *HashFunc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashFunc.Marshal(b, m, deterministic)
}
func (m *HashFunc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashFunc.Merge(m, src)
}
func (m *HashFunc) XXX_Size() int {
	return xxx_messageInfo_HashFunc.Size(m)
}
func (m *HashFunc) XXX_DiscardUnknown() {
	xxx_messageInfo_HashFunc.DiscardUnknown(m)
}

var xxx_messageInfo_HashFunc proto.InternalMessageInfo

func (m *HashFunc) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *HashFunc) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *HashFunc) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type NetAddress struct {
	Timestamp            *Time    `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Tervices             uint64   `protobuf:"varint,2,opt,name=tervices,proto3" json:"tervices,omitempty"`
	IP                   []byte   `protobuf:"bytes,3,opt,name=IP,proto3" json:"IP,omitempty"`
	Port                 uint32   `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetAddress) Reset()         { *m = NetAddress{} }
func (m *NetAddress) String() string { return proto.CompactTextString(m) }
func (*NetAddress) ProtoMessage()    {}
func (*NetAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{1}
}

func (m *NetAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetAddress.Unmarshal(m, b)
}
func (m *NetAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetAddress.Marshal(b, m, deterministic)
}
func (m *NetAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetAddress.Merge(m, src)
}
func (m *NetAddress) XXX_Size() int {
	return xxx_messageInfo_NetAddress.Size(m)
}
func (m *NetAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_NetAddress.DiscardUnknown(m)
}

var xxx_messageInfo_NetAddress proto.InternalMessageInfo

func (m *NetAddress) GetTimestamp() *Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *NetAddress) GetTervices() uint64 {
	if m != nil {
		return m.Tervices
	}
	return 0
}

func (m *NetAddress) GetIP() []byte {
	if m != nil {
		return m.IP
	}
	return nil
}

func (m *NetAddress) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type HostToNetAddrFunc struct {
	Address              *NetAddress `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Error                string      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HostToNetAddrFunc) Reset()         { *m = HostToNetAddrFunc{} }
func (m *HostToNetAddrFunc) String() string { return proto.CompactTextString(m) }
func (*HostToNetAddrFunc) ProtoMessage()    {}
func (*HostToNetAddrFunc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{2}
}

func (m *HostToNetAddrFunc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostToNetAddrFunc.Unmarshal(m, b)
}
func (m *HostToNetAddrFunc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostToNetAddrFunc.Marshal(b, m, deterministic)
}
func (m *HostToNetAddrFunc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostToNetAddrFunc.Merge(m, src)
}
func (m *HostToNetAddrFunc) XXX_Size() int {
	return xxx_messageInfo_HostToNetAddrFunc.Size(m)
}
func (m *HostToNetAddrFunc) XXX_DiscardUnknown() {
	xxx_messageInfo_HostToNetAddrFunc.DiscardUnknown(m)
}

var xxx_messageInfo_HostToNetAddrFunc proto.InternalMessageInfo

func (m *HostToNetAddrFunc) GetAddress() *NetAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *HostToNetAddrFunc) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DNSSeed struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	HasFiltering         bool     `protobuf:"varint,2,opt,name=has_filtering,json=hasFiltering,proto3" json:"has_filtering,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DNSSeed) Reset()         { *m = DNSSeed{} }
func (m *DNSSeed) String() string { return proto.CompactTextString(m) }
func (*DNSSeed) ProtoMessage()    {}
func (*DNSSeed) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{3}
}

func (m *DNSSeed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DNSSeed.Unmarshal(m, b)
}
func (m *DNSSeed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DNSSeed.Marshal(b, m, deterministic)
}
func (m *DNSSeed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DNSSeed.Merge(m, src)
}
func (m *DNSSeed) XXX_Size() int {
	return xxx_messageInfo_DNSSeed.Size(m)
}
func (m *DNSSeed) XXX_DiscardUnknown() {
	xxx_messageInfo_DNSSeed.DiscardUnknown(m)
}

var xxx_messageInfo_DNSSeed proto.InternalMessageInfo

func (m *DNSSeed) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *DNSSeed) GetHasFiltering() bool {
	if m != nil {
		return m.HasFiltering
	}
	return false
}

type CoinAmount struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProperName           string   `protobuf:"bytes,2,opt,name=proper_name,json=properName,proto3" json:"proper_name,omitempty"`
	Units                int64    `protobuf:"varint,3,opt,name=units,proto3" json:"units,omitempty"`
	Zeros                int32    `protobuf:"varint,4,opt,name=zeros,proto3" json:"zeros,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinAmount) Reset()         { *m = CoinAmount{} }
func (m *CoinAmount) String() string { return proto.CompactTextString(m) }
func (*CoinAmount) ProtoMessage()    {}
func (*CoinAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{4}
}

func (m *CoinAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinAmount.Unmarshal(m, b)
}
func (m *CoinAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinAmount.Marshal(b, m, deterministic)
}
func (m *CoinAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinAmount.Merge(m, src)
}
func (m *CoinAmount) XXX_Size() int {
	return xxx_messageInfo_CoinAmount.Size(m)
}
func (m *CoinAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinAmount.DiscardUnknown(m)
}

var xxx_messageInfo_CoinAmount proto.InternalMessageInfo

func (m *CoinAmount) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CoinAmount) GetProperName() string {
	if m != nil {
		return m.ProperName
	}
	return ""
}

func (m *CoinAmount) GetUnits() int64 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *CoinAmount) GetZeros() int32 {
	if m != nil {
		return m.Zeros
	}
	return 0
}

type GlobalConfig struct {
	ProofOfWorkAlgorithm int32       `protobuf:"varint,1,opt,name=proof_of_work_algorithm,json=proofOfWorkAlgorithm,proto3" json:"proof_of_work_algorithm,omitempty"`
	HasNetworkSteward    bool        `protobuf:"varint,2,opt,name=has_network_steward,json=hasNetworkSteward,proto3" json:"has_network_steward,omitempty"`
	MaxUnits             int64       `protobuf:"varint,3,opt,name=max_units,json=maxUnits,proto3" json:"max_units,omitempty"`
	UnitsPerCoin         int64       `protobuf:"varint,4,opt,name=units_per_coin,json=unitsPerCoin,proto3" json:"units_per_coin,omitempty"`
	MaxTimeOffset        int64       `protobuf:"varint,5,opt,name=max_time_offset,json=maxTimeOffset,proto3" json:"max_time_offset,omitempty"`
	MedianTimeBlocks     int32       `protobuf:"varint,6,opt,name=median_time_blocks,json=medianTimeBlocks,proto3" json:"median_time_blocks,omitempty"`
	Amounts              *CoinAmount `protobuf:"bytes,7,opt,name=amounts,proto3" json:"amounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GlobalConfig) Reset()         { *m = GlobalConfig{} }
func (m *GlobalConfig) String() string { return proto.CompactTextString(m) }
func (*GlobalConfig) ProtoMessage()    {}
func (*GlobalConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{5}
}

func (m *GlobalConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalConfig.Unmarshal(m, b)
}
func (m *GlobalConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalConfig.Marshal(b, m, deterministic)
}
func (m *GlobalConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalConfig.Merge(m, src)
}
func (m *GlobalConfig) XXX_Size() int {
	return xxx_messageInfo_GlobalConfig.Size(m)
}
func (m *GlobalConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalConfig proto.InternalMessageInfo

func (m *GlobalConfig) GetProofOfWorkAlgorithm() int32 {
	if m != nil {
		return m.ProofOfWorkAlgorithm
	}
	return 0
}

func (m *GlobalConfig) GetHasNetworkSteward() bool {
	if m != nil {
		return m.HasNetworkSteward
	}
	return false
}

func (m *GlobalConfig) GetMaxUnits() int64 {
	if m != nil {
		return m.MaxUnits
	}
	return 0
}

func (m *GlobalConfig) GetUnitsPerCoin() int64 {
	if m != nil {
		return m.UnitsPerCoin
	}
	return 0
}

func (m *GlobalConfig) GetMaxTimeOffset() int64 {
	if m != nil {
		return m.MaxTimeOffset
	}
	return 0
}

func (m *GlobalConfig) GetMedianTimeBlocks() int32 {
	if m != nil {
		return m.MedianTimeBlocks
	}
	return 0
}

func (m *GlobalConfig) GetAmounts() *CoinAmount {
	if m != nil {
		return m.Amounts
	}
	return nil
}

type Params struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Net                  uint32        `protobuf:"varint,2,opt,name=net,proto3" json:"net,omitempty"`
	DefaultPort          string        `protobuf:"bytes,3,opt,name=default_port,json=defaultPort,proto3" json:"default_port,omitempty"`
	DNSSeed              *DNSSeed      `protobuf:"bytes,4,opt,name=DNSSeed,proto3" json:"DNSSeed,omitempty"`
	Config               *GlobalConfig `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{6}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Params) GetNet() uint32 {
	if m != nil {
		return m.Net
	}
	return 0
}

func (m *Params) GetDefaultPort() string {
	if m != nil {
		return m.DefaultPort
	}
	return ""
}

func (m *Params) GetDNSSeed() *DNSSeed {
	if m != nil {
		return m.DNSSeed
	}
	return nil
}

func (m *Params) GetConfig() *GlobalConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type MessageListeners struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageListeners) Reset()         { *m = MessageListeners{} }
func (m *MessageListeners) String() string { return proto.CompactTextString(m) }
func (*MessageListeners) ProtoMessage()    {}
func (*MessageListeners) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{7}
}

func (m *MessageListeners) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageListeners.Unmarshal(m, b)
}
func (m *MessageListeners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageListeners.Marshal(b, m, deterministic)
}
func (m *MessageListeners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageListeners.Merge(m, src)
}
func (m *MessageListeners) XXX_Size() int {
	return xxx_messageInfo_MessageListeners.Size(m)
}
func (m *MessageListeners) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageListeners.DiscardUnknown(m)
}

var xxx_messageInfo_MessageListeners proto.InternalMessageInfo

type Config struct {
	NewestBlock          *HashFunc          `protobuf:"bytes,1,opt,name=newest_block,json=newestBlock,proto3" json:"newest_block,omitempty"`
	HostToNetAddrFunc    *HostToNetAddrFunc `protobuf:"bytes,2,opt,name=host_to_net_addr_func,json=hostToNetAddrFunc,proto3" json:"host_to_net_addr_func,omitempty"`
	UserAgentName        string             `protobuf:"bytes,3,opt,name=user_agent_name,json=userAgentName,proto3" json:"user_agent_name,omitempty"`
	UserAgentVersion     string             `protobuf:"bytes,4,opt,name=user_agent_version,json=userAgentVersion,proto3" json:"user_agent_version,omitempty"`
	UserAgentComments    string             `protobuf:"bytes,5,opt,name=user_agent_comments,json=userAgentComments,proto3" json:"user_agent_comments,omitempty"`
	ChainParams          *Params            `protobuf:"bytes,6,opt,name=chain_params,json=chainParams,proto3" json:"chain_params,omitempty"`
	Services             uint64             `protobuf:"varint,7,opt,name=services,proto3" json:"services,omitempty"`
	ProtocolVersion      uint32             `protobuf:"varint,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	DisableRelayTx       bool               `protobuf:"varint,9,opt,name=disable_relay_tx,json=disableRelayTx,proto3" json:"disable_relay_tx,omitempty"`
	Listeners            *MessageListeners  `protobuf:"bytes,10,opt,name=listeners,proto3" json:"listeners,omitempty"`
	TrickleInterval      int64              `protobuf:"varint,11,opt,name=trickle_interval,json=trickleInterval,proto3" json:"trickle_interval,omitempty"`
	AllowSelfConns       bool               `protobuf:"varint,12,opt,name=allow_self_conns,json=allowSelfConns,proto3" json:"allow_self_conns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{8}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetNewestBlock() *HashFunc {
	if m != nil {
		return m.NewestBlock
	}
	return nil
}

func (m *Config) GetHostToNetAddrFunc() *HostToNetAddrFunc {
	if m != nil {
		return m.HostToNetAddrFunc
	}
	return nil
}

func (m *Config) GetUserAgentName() string {
	if m != nil {
		return m.UserAgentName
	}
	return ""
}

func (m *Config) GetUserAgentVersion() string {
	if m != nil {
		return m.UserAgentVersion
	}
	return ""
}

func (m *Config) GetUserAgentComments() string {
	if m != nil {
		return m.UserAgentComments
	}
	return ""
}

func (m *Config) GetChainParams() *Params {
	if m != nil {
		return m.ChainParams
	}
	return nil
}

func (m *Config) GetServices() uint64 {
	if m != nil {
		return m.Services
	}
	return 0
}

func (m *Config) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *Config) GetDisableRelayTx() bool {
	if m != nil {
		return m.DisableRelayTx
	}
	return false
}

func (m *Config) GetListeners() *MessageListeners {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func (m *Config) GetTrickleInterval() int64 {
	if m != nil {
		return m.TrickleInterval
	}
	return 0
}

func (m *Config) GetAllowSelfConns() bool {
	if m != nil {
		return m.AllowSelfConns
	}
	return false
}

type ZoneTrans struct {
	When                 int64    `protobuf:"varint,1,opt,name=when,proto3" json:"when,omitempty"`
	Index                uint32   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Isstd                bool     `protobuf:"varint,3,opt,name=isstd,proto3" json:"isstd,omitempty"`
	Isutc                bool     `protobuf:"varint,4,opt,name=isutc,proto3" json:"isutc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneTrans) Reset()         { *m = ZoneTrans{} }
func (m *ZoneTrans) String() string { return proto.CompactTextString(m) }
func (*ZoneTrans) ProtoMessage()    {}
func (*ZoneTrans) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{9}
}

func (m *ZoneTrans) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneTrans.Unmarshal(m, b)
}
func (m *ZoneTrans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneTrans.Marshal(b, m, deterministic)
}
func (m *ZoneTrans) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneTrans.Merge(m, src)
}
func (m *ZoneTrans) XXX_Size() int {
	return xxx_messageInfo_ZoneTrans.Size(m)
}
func (m *ZoneTrans) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneTrans.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneTrans proto.InternalMessageInfo

func (m *ZoneTrans) GetWhen() int64 {
	if m != nil {
		return m.When
	}
	return 0
}

func (m *ZoneTrans) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *ZoneTrans) GetIsstd() bool {
	if m != nil {
		return m.Isstd
	}
	return false
}

func (m *ZoneTrans) GetIsutc() bool {
	if m != nil {
		return m.Isutc
	}
	return false
}

type Zone struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Offset               int32    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	IsDST                bool     `protobuf:"varint,3,opt,name=isDST,proto3" json:"isDST,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{10}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Zone) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Zone) GetIsDST() bool {
	if m != nil {
		return m.IsDST
	}
	return false
}

type Location struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Zone                 *Zone      `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	Tx                   *ZoneTrans `protobuf:"bytes,3,opt,name=tx,proto3" json:"tx,omitempty"`
	Extend               string     `protobuf:"bytes,4,opt,name=extend,proto3" json:"extend,omitempty"`
	CacheStart           int64      `protobuf:"varint,5,opt,name=cache_start,json=cacheStart,proto3" json:"cache_start,omitempty"`
	CacheEnd             int64      `protobuf:"varint,6,opt,name=cache_end,json=cacheEnd,proto3" json:"cache_end,omitempty"`
	CacheZone            *Zone      `protobuf:"bytes,7,opt,name=cache_zone,json=cacheZone,proto3" json:"cache_zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{11}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Location) GetZone() *Zone {
	if m != nil {
		return m.Zone
	}
	return nil
}

func (m *Location) GetTx() *ZoneTrans {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *Location) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *Location) GetCacheStart() int64 {
	if m != nil {
		return m.CacheStart
	}
	return 0
}

func (m *Location) GetCacheEnd() int64 {
	if m != nil {
		return m.CacheEnd
	}
	return 0
}

func (m *Location) GetCacheZone() *Zone {
	if m != nil {
		return m.CacheZone
	}
	return nil
}

type Time struct {
	Wall                 uint64    `protobuf:"varint,1,opt,name=wall,proto3" json:"wall,omitempty"`
	Ext                  int64     `protobuf:"varint,2,opt,name=ext,proto3" json:"ext,omitempty"`
	Loc                  *Location `protobuf:"bytes,3,opt,name=loc,proto3" json:"loc,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{12}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetWall() uint64 {
	if m != nil {
		return m.Wall
	}
	return 0
}

func (m *Time) GetExt() int64 {
	if m != nil {
		return m.Ext
	}
	return 0
}

func (m *Time) GetLoc() *Location {
	if m != nil {
		return m.Loc
	}
	return nil
}

type PeerDesc struct {
	BytesReceived        uint64      `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	BytesSent            uint64      `protobuf:"varint,2,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	LastRecv             *Time       `protobuf:"bytes,3,opt,name=last_recv,json=lastRecv,proto3" json:"last_recv,omitempty"`
	LastSend             *Time       `protobuf:"bytes,4,opt,name=last_send,json=lastSend,proto3" json:"last_send,omitempty"`
	Connected            bool        `protobuf:"varint,5,opt,name=connected,proto3" json:"connected,omitempty"`
	Addr                 string      `protobuf:"bytes,6,opt,name=addr,proto3" json:"addr,omitempty"`
	Cfg                  *Config     `protobuf:"bytes,7,opt,name=cfg,proto3" json:"cfg,omitempty"`
	Inbound              bool        `protobuf:"varint,8,opt,name=inbound,proto3" json:"inbound,omitempty"`
	Na                   *NetAddress `protobuf:"bytes,9,opt,name=na,proto3" json:"na,omitempty"`
	Id                   int32       `protobuf:"varint,10,opt,name=id,proto3" json:"id,omitempty"`
	UserAgent            string      `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Services             uint64      `protobuf:"varint,12,opt,name=services,proto3" json:"services,omitempty"`
	VersionKnown         bool        `protobuf:"varint,13,opt,name=version_known,json=versionKnown,proto3" json:"version_known,omitempty"`
	AdvertisedProtoVer   uint32      `protobuf:"varint,14,opt,name=advertised_proto_ver,json=advertisedProtoVer,proto3" json:"advertised_proto_ver,omitempty"`
	ProtocolVersion      uint32      `protobuf:"varint,15,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SendHeadersPreferred bool        `protobuf:"varint,16,opt,name=send_headers_preferred,json=sendHeadersPreferred,proto3" json:"send_headers_preferred,omitempty"`
	VerAckReceived       bool        `protobuf:"varint,17,opt,name=ver_ack_received,json=verAckReceived,proto3" json:"ver_ack_received,omitempty"`
	WitnessEnabled       bool        `protobuf:"varint,18,opt,name=witness_enabled,json=witnessEnabled,proto3" json:"witness_enabled,omitempty"`
	WireEncoding         uint32      `protobuf:"varint,19,opt,name=wire_encoding,json=wireEncoding,proto3" json:"wire_encoding,omitempty"`
	TimeOffset           int64       `protobuf:"varint,20,opt,name=time_offset,json=timeOffset,proto3" json:"time_offset,omitempty"`
	TimeConnected        *Time       `protobuf:"bytes,21,opt,name=time_connected,json=timeConnected,proto3" json:"time_connected,omitempty"`
	StartingHeight       int32       `protobuf:"varint,22,opt,name=starting_height,json=startingHeight,proto3" json:"starting_height,omitempty"`
	LastBlock            int32       `protobuf:"varint,23,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	LastAnnouncedBlock   []byte      `protobuf:"bytes,24,opt,name=last_announced_block,json=lastAnnouncedBlock,proto3" json:"last_announced_block,omitempty"`
	LastPingNonce        uint64      `protobuf:"varint,25,opt,name=last_ping_nonce,json=lastPingNonce,proto3" json:"last_ping_nonce,omitempty"`
	LastPingTime         *Time       `protobuf:"bytes,26,opt,name=last_ping_time,json=lastPingTime,proto3" json:"last_ping_time,omitempty"`
	LastPingMicros       int64       `protobuf:"varint,27,opt,name=last_ping_micros,json=lastPingMicros,proto3" json:"last_ping_micros,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PeerDesc) Reset()         { *m = PeerDesc{} }
func (m *PeerDesc) String() string { return proto.CompactTextString(m) }
func (*PeerDesc) ProtoMessage()    {}
func (*PeerDesc) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{13}
}

func (m *PeerDesc) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerDesc.Unmarshal(m, b)
}
func (m *PeerDesc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerDesc.Marshal(b, m, deterministic)
}
func (m *PeerDesc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerDesc.Merge(m, src)
}
func (m *PeerDesc) XXX_Size() int {
	return xxx_messageInfo_PeerDesc.Size(m)
}
func (m *PeerDesc) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerDesc.DiscardUnknown(m)
}

var xxx_messageInfo_PeerDesc proto.InternalMessageInfo

func (m *PeerDesc) GetBytesReceived() uint64 {
	if m != nil {
		return m.BytesReceived
	}
	return 0
}

func (m *PeerDesc) GetBytesSent() uint64 {
	if m != nil {
		return m.BytesSent
	}
	return 0
}

func (m *PeerDesc) GetLastRecv() *Time {
	if m != nil {
		return m.LastRecv
	}
	return nil
}

func (m *PeerDesc) GetLastSend() *Time {
	if m != nil {
		return m.LastSend
	}
	return nil
}

func (m *PeerDesc) GetConnected() bool {
	if m != nil {
		return m.Connected
	}
	return false
}

func (m *PeerDesc) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func (m *PeerDesc) GetCfg() *Config {
	if m != nil {
		return m.Cfg
	}
	return nil
}

func (m *PeerDesc) GetInbound() bool {
	if m != nil {
		return m.Inbound
	}
	return false
}

func (m *PeerDesc) GetNa() *NetAddress {
	if m != nil {
		return m.Na
	}
	return nil
}

func (m *PeerDesc) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PeerDesc) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *PeerDesc) GetServices() uint64 {
	if m != nil {
		return m.Services
	}
	return 0
}

func (m *PeerDesc) GetVersionKnown() bool {
	if m != nil {
		return m.VersionKnown
	}
	return false
}

func (m *PeerDesc) GetAdvertisedProtoVer() uint32 {
	if m != nil {
		return m.AdvertisedProtoVer
	}
	return 0
}

func (m *PeerDesc) GetProtocolVersion() uint32 {
	if m != nil {
		return m.ProtocolVersion
	}
	return 0
}

func (m *PeerDesc) GetSendHeadersPreferred() bool {
	if m != nil {
		return m.SendHeadersPreferred
	}
	return false
}

func (m *PeerDesc) GetVerAckReceived() bool {
	if m != nil {
		return m.VerAckReceived
	}
	return false
}

func (m *PeerDesc) GetWitnessEnabled() bool {
	if m != nil {
		return m.WitnessEnabled
	}
	return false
}

func (m *PeerDesc) GetWireEncoding() uint32 {
	if m != nil {
		return m.WireEncoding
	}
	return 0
}

func (m *PeerDesc) GetTimeOffset() int64 {
	if m != nil {
		return m.TimeOffset
	}
	return 0
}

func (m *PeerDesc) GetTimeConnected() *Time {
	if m != nil {
		return m.TimeConnected
	}
	return nil
}

func (m *PeerDesc) GetStartingHeight() int32 {
	if m != nil {
		return m.StartingHeight
	}
	return 0
}

func (m *PeerDesc) GetLastBlock() int32 {
	if m != nil {
		return m.LastBlock
	}
	return 0
}

func (m *PeerDesc) GetLastAnnouncedBlock() []byte {
	if m != nil {
		return m.LastAnnouncedBlock
	}
	return nil
}

func (m *PeerDesc) GetLastPingNonce() uint64 {
	if m != nil {
		return m.LastPingNonce
	}
	return 0
}

func (m *PeerDesc) GetLastPingTime() *Time {
	if m != nil {
		return m.LastPingTime
	}
	return nil
}

func (m *PeerDesc) GetLastPingMicros() int64 {
	if m != nil {
		return m.LastPingMicros
	}
	return 0
}

type WalletStats struct {
	MaintenanceInProgress       bool     `protobuf:"varint,1,opt,name=maintenance_in_progress,json=maintenanceInProgress,proto3" json:"maintenance_in_progress,omitempty"`
	MaintenanceName             string   `protobuf:"bytes,2,opt,name=maintenance_name,json=maintenanceName,proto3" json:"maintenance_name,omitempty"`
	MaintenanceCycles           int32    `protobuf:"varint,3,opt,name=maintenance_cycles,json=maintenanceCycles,proto3" json:"maintenance_cycles,omitempty"`
	MaintenanceLastBlockVisited int32    `protobuf:"varint,4,opt,name=maintenance_last_block_visited,json=maintenanceLastBlockVisited,proto3" json:"maintenance_last_block_visited,omitempty"`
	TimeOfLastMaintenance       *Time    `protobuf:"bytes,5,opt,name=time_of_last_maintenance,json=timeOfLastMaintenance,proto3" json:"time_of_last_maintenance,omitempty"`
	Syncing                     bool     `protobuf:"varint,6,opt,name=syncing,proto3" json:"syncing,omitempty"`
	SyncStarted                 *Time    `protobuf:"bytes,7,opt,name=sync_started,json=syncStarted,proto3" json:"sync_started,omitempty"`
	SyncRemainingSeconds        int64    `protobuf:"varint,8,opt,name=sync_remaining_seconds,json=syncRemainingSeconds,proto3" json:"sync_remaining_seconds,omitempty"`
	SyncCurrentBlock            int32    `protobuf:"varint,9,opt,name=sync_current_block,json=syncCurrentBlock,proto3" json:"sync_current_block,omitempty"`
	SyncFrom                    int32    `protobuf:"varint,10,opt,name=sync_from,json=syncFrom,proto3" json:"sync_from,omitempty"`
	SyncTo                      int32    `protobuf:"varint,11,opt,name=sync_to,json=syncTo,proto3" json:"sync_to,omitempty"`
	BirthdayBlock               int32    `protobuf:"varint,12,opt,name=birthday_block,json=birthdayBlock,proto3" json:"birthday_block,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *WalletStats) Reset()         { *m = WalletStats{} }
func (m *WalletStats) String() string { return proto.CompactTextString(m) }
func (*WalletStats) ProtoMessage()    {}
func (*WalletStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c5f63a845a51abc, []int{14}
}

func (m *WalletStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletStats.Unmarshal(m, b)
}
func (m *WalletStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletStats.Marshal(b, m, deterministic)
}
func (m *WalletStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletStats.Merge(m, src)
}
func (m *WalletStats) XXX_Size() int {
	return xxx_messageInfo_WalletStats.Size(m)
}
func (m *WalletStats) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletStats.DiscardUnknown(m)
}

var xxx_messageInfo_WalletStats proto.InternalMessageInfo

func (m *WalletStats) GetMaintenanceInProgress() bool {
	if m != nil {
		return m.MaintenanceInProgress
	}
	return false
}

func (m *WalletStats) GetMaintenanceName() string {
	if m != nil {
		return m.MaintenanceName
	}
	return ""
}

func (m *WalletStats) GetMaintenanceCycles() int32 {
	if m != nil {
		return m.MaintenanceCycles
	}
	return 0
}

func (m *WalletStats) GetMaintenanceLastBlockVisited() int32 {
	if m != nil {
		return m.MaintenanceLastBlockVisited
	}
	return 0
}

func (m *WalletStats) GetTimeOfLastMaintenance() *Time {
	if m != nil {
		return m.TimeOfLastMaintenance
	}
	return nil
}

func (m *WalletStats) GetSyncing() bool {
	if m != nil {
		return m.Syncing
	}
	return false
}

func (m *WalletStats) GetSyncStarted() *Time {
	if m != nil {
		return m.SyncStarted
	}
	return nil
}

func (m *WalletStats) GetSyncRemainingSeconds() int64 {
	if m != nil {
		return m.SyncRemainingSeconds
	}
	return 0
}

func (m *WalletStats) GetSyncCurrentBlock() int32 {
	if m != nil {
		return m.SyncCurrentBlock
	}
	return 0
}

func (m *WalletStats) GetSyncFrom() int32 {
	if m != nil {
		return m.SyncFrom
	}
	return 0
}

func (m *WalletStats) GetSyncTo() int32 {
	if m != nil {
		return m.SyncTo
	}
	return 0
}

func (m *WalletStats) GetBirthdayBlock() int32 {
	if m != nil {
		return m.BirthdayBlock
	}
	return 0
}

func init() {
	proto.RegisterType((*HashFunc)(nil), "lnrpc.hash_func")
	proto.RegisterType((*NetAddress)(nil), "lnrpc.net_address")
	proto.RegisterType((*HostToNetAddrFunc)(nil), "lnrpc.host_to_net_addr_func")
	proto.RegisterType((*DNSSeed)(nil), "lnrpc.DNSSeed")
	proto.RegisterType((*CoinAmount)(nil), "lnrpc.coin_amount")
	proto.RegisterType((*GlobalConfig)(nil), "lnrpc.global_config")
	proto.RegisterType((*Params)(nil), "lnrpc.params")
	proto.RegisterType((*MessageListeners)(nil), "lnrpc.message_listeners")
	proto.RegisterType((*Config)(nil), "lnrpc.Config")
	proto.RegisterType((*ZoneTrans)(nil), "lnrpc.zoneTrans")
	proto.RegisterType((*Zone)(nil), "lnrpc.zone")
	proto.RegisterType((*Location)(nil), "lnrpc.Location")
	proto.RegisterType((*Time)(nil), "lnrpc.time")
	proto.RegisterType((*PeerDesc)(nil), "lnrpc.peer_desc")
	proto.RegisterType((*WalletStats)(nil), "lnrpc.wallet_stats")
}

func init() { proto.RegisterFile("pkt.proto", fileDescriptor_3c5f63a845a51abc) }

var fileDescriptor_3c5f63a845a51abc = []byte{
	// 1740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x56, 0x5f, 0x73, 0x1b, 0xb7,
	0x11, 0x1f, 0x51, 0x22, 0x45, 0x2e, 0xff, 0x49, 0xb0, 0x6c, 0x5f, 0xed, 0xa4, 0x71, 0x98, 0xd4,
	0x51, 0x3a, 0x8e, 0xe2, 0x2a, 0x6d, 0xde, 0x6d, 0xd9, 0x1e, 0x7b, 0x1a, 0xcb, 0x1a, 0x50, 0x75,
	0x67, 0xd2, 0x87, 0x1b, 0xe8, 0x6e, 0x49, 0xde, 0xe8, 0x0e, 0xe0, 0x00, 0xa0, 0x44, 0xe5, 0xbd,
	0x1f, 0xa6, 0x5f, 0xa0, 0x6f, 0x7d, 0xea, 0x47, 0xe9, 0x17, 0xe9, 0xec, 0x02, 0x47, 0x52, 0xb1,
	0xf2, 0x40, 0x0e, 0xf0, 0xdb, 0x1f, 0x70, 0x8b, 0xc5, 0xee, 0x0f, 0x0b, 0x9d, 0xf9, 0xa5, 0x3f,
	0x9a, 0x5b, 0xe3, 0x8d, 0x68, 0x96, 0xda, 0xce, 0xb3, 0xd1, 0x7b, 0xe8, 0xcc, 0x94, 0x9b, 0xa5,
	0x93, 0x85, 0xce, 0x84, 0x80, 0x1d, 0x9a, 0x24, 0x5b, 0x4f, 0xb6, 0x0e, 0x7b, 0x92, 0xc7, 0xe2,
	0x01, 0xb4, 0x66, 0x58, 0x4c, 0x67, 0x3e, 0x69, 0x3c, 0xd9, 0x3a, 0x6c, 0xca, 0x38, 0x13, 0x07,
	0xd0, 0x44, 0x6b, 0x8d, 0x4d, 0xb6, 0x9f, 0x6c, 0x1d, 0x76, 0x64, 0x98, 0x8c, 0x96, 0xd0, 0xd5,
	0xe8, 0x53, 0x95, 0xe7, 0x16, 0x9d, 0x13, 0xdf, 0x42, 0xc7, 0x17, 0x15, 0x3a, 0xaf, 0xaa, 0x39,
	0xef, 0xda, 0x3d, 0xee, 0x1e, 0xf1, 0x87, 0x8f, 0x08, 0x97, 0x6b, 0xab, 0x78, 0x04, 0x6d, 0x8f,
	0xf6, 0xaa, 0xc8, 0xd0, 0xf1, 0x97, 0x76, 0xe4, 0x6a, 0x2e, 0x06, 0xd0, 0x78, 0x77, 0xc6, 0x1f,
	0xea, 0xc9, 0xc6, 0xbb, 0x33, 0xf2, 0x73, 0x6e, 0xac, 0x4f, 0x76, 0x9e, 0x6c, 0x1d, 0xf6, 0x25,
	0x8f, 0x47, 0xff, 0x80, 0xfb, 0x33, 0xe3, 0x7c, 0xea, 0x4d, 0x5a, 0x7b, 0x10, 0x0e, 0xf5, 0x0c,
	0x76, 0xa3, 0x3b, 0xd1, 0x03, 0x11, 0x3d, 0xd8, 0x70, 0x54, 0xd6, 0x94, 0xf5, 0xb1, 0x1a, 0x9b,
	0xc7, 0x7a, 0x09, 0xbb, 0xaf, 0x4e, 0xc7, 0x63, 0xc4, 0x9c, 0x63, 0x64, 0x9c, 0xe7, 0xbd, 0x3a,
	0x92, 0xc7, 0xe2, 0x2b, 0xe8, 0xcf, 0x94, 0x4b, 0x27, 0x45, 0xe9, 0xd1, 0x16, 0x7a, 0xca, 0x8b,
	0xdb, 0xb2, 0x37, 0x53, 0xee, 0x4d, 0x8d, 0x8d, 0x34, 0x74, 0x33, 0x53, 0xe8, 0x54, 0x55, 0x66,
	0xa1, 0x3d, 0xed, 0xa3, 0x55, 0x85, 0xf5, 0x3e, 0x34, 0x16, 0x5f, 0x40, 0x77, 0x6e, 0xcd, 0x1c,
	0x6d, 0xca, 0xa6, 0xe0, 0x02, 0x04, 0xe8, 0x94, 0x08, 0x07, 0xd0, 0x5c, 0xe8, 0xc2, 0x3b, 0x8e,
	0xc5, 0xb6, 0x0c, 0x13, 0x42, 0x7f, 0x41, 0x6b, 0x1c, 0xc7, 0xa3, 0x29, 0xc3, 0x64, 0xf4, 0x9f,
	0x06, 0xf4, 0xa7, 0xa5, 0xb9, 0x50, 0x65, 0x9a, 0x19, 0x3d, 0x29, 0xa6, 0xe2, 0x2f, 0xf0, 0x70,
	0x6e, 0x8d, 0x99, 0xa4, 0x66, 0x92, 0x5e, 0x1b, 0x7b, 0x99, 0xaa, 0x72, 0x6a, 0x6c, 0xe1, 0x67,
	0x15, 0x7b, 0xd1, 0x94, 0x07, 0x6c, 0xfe, 0x30, 0xf9, 0xbb, 0xb1, 0x97, 0x2f, 0x6a, 0x9b, 0x38,
	0x82, 0x7b, 0x74, 0x3a, 0x8d, 0x9e, 0x17, 0x39, 0x8f, 0xd7, 0xca, 0xe6, 0xf1, 0x8c, 0xfb, 0x33,
	0xe5, 0x4e, 0x83, 0x65, 0x1c, 0x0c, 0xe2, 0x31, 0x74, 0x2a, 0xb5, 0x4c, 0x37, 0x1d, 0x6d, 0x57,
	0x6a, 0xf9, 0x37, 0xf6, 0xf5, 0x6b, 0x18, 0xb0, 0x21, 0xa5, 0x53, 0x52, 0x3c, 0xd8, 0xe9, 0x6d,
	0xd9, 0x63, 0xf4, 0x0c, 0xed, 0x89, 0x29, 0xb4, 0x78, 0x0a, 0x43, 0xda, 0x82, 0xb2, 0x23, 0x35,
	0x93, 0x89, 0x43, 0x9f, 0x34, 0x99, 0xd6, 0xaf, 0xd4, 0xf2, 0xbc, 0xa8, 0xf0, 0x03, 0x83, 0xe2,
	0x19, 0x88, 0x0a, 0xf3, 0x42, 0xe9, 0x40, 0xbd, 0x28, 0x4d, 0x76, 0xe9, 0x92, 0x16, 0x1f, 0x66,
	0x2f, 0x58, 0x88, 0xfd, 0x92, 0x71, 0xce, 0x04, 0x0e, 0xbe, 0x4b, 0x76, 0x6f, 0x65, 0xc2, 0xc6,
	0xbd, 0xc8, 0x9a, 0x32, 0xfa, 0xd7, 0x16, 0xb4, 0xe6, 0xca, 0xaa, 0xca, 0xdd, 0x79, 0x57, 0x7b,
	0xb0, 0xad, 0x31, 0x14, 0x45, 0x5f, 0xd2, 0x50, 0x7c, 0x09, 0xbd, 0x1c, 0x27, 0x6a, 0x51, 0xfa,
	0x94, 0xb3, 0x33, 0x14, 0x46, 0x37, 0x62, 0x67, 0xc6, 0x7a, 0x71, 0xb8, 0xca, 0x23, 0x3e, 0x76,
	0xf7, 0x78, 0x10, 0x3d, 0x88, 0xa8, 0x5c, 0xa5, 0xd9, 0x33, 0x68, 0x85, 0x5b, 0xe3, 0x83, 0x77,
	0x8f, 0x0f, 0x22, 0xf1, 0xd6, 0x8d, 0xca, 0xc8, 0x19, 0xdd, 0x83, 0xfd, 0x0a, 0x9d, 0x53, 0x53,
	0x4c, 0xcb, 0xc2, 0x79, 0xd4, 0x68, 0xdd, 0xe8, 0xbf, 0x3b, 0xd0, 0x3a, 0x09, 0x37, 0xff, 0x03,
	0xf4, 0x34, 0x5e, 0xa3, 0xf3, 0x21, 0x44, 0xb1, 0x10, 0xf6, 0xe2, 0x9e, 0x2b, 0x01, 0x90, 0xdd,
	0xc0, 0xe2, 0x78, 0x89, 0xd3, 0xdf, 0xa8, 0x28, 0x3e, 0x73, 0xf7, 0xf8, 0xb3, 0x7a, 0xf5, 0x5d,
	0x1c, 0xb9, 0x4f, 0xf0, 0xb9, 0x39, 0x45, 0xff, 0x22, 0xcf, 0xed, 0x1b, 0x2a, 0xc4, 0xa7, 0x30,
	0x5c, 0x38, 0xb4, 0xa9, 0x9a, 0xa2, 0xf6, 0x21, 0xc3, 0x43, 0x88, 0xfa, 0x04, 0xbf, 0x20, 0x94,
	0x93, 0xfc, 0x19, 0x88, 0x0d, 0xde, 0x15, 0x5a, 0x57, 0x98, 0x90, 0x26, 0x1d, 0xb9, 0xb7, 0xa2,
	0x7e, 0x0c, 0x38, 0x65, 0xe7, 0x06, 0x3b, 0x33, 0x55, 0x85, 0x74, 0xc1, 0x4d, 0xa6, 0xef, 0xaf,
	0xe8, 0x27, 0xd1, 0x20, 0x9e, 0x43, 0x2f, 0x9b, 0xa9, 0x42, 0xa7, 0xe1, 0x6e, 0x39, 0x59, 0xba,
	0xc7, 0xfd, 0x78, 0x98, 0x00, 0xca, 0x2e, 0x53, 0xce, 0xc2, 0xed, 0x3f, 0x82, 0xb6, 0xab, 0x95,
	0x69, 0x37, 0x28, 0x53, 0x3d, 0x17, 0xdf, 0xc2, 0x1e, 0xcb, 0x69, 0x66, 0xca, 0x95, 0xa7, 0x6d,
	0x4e, 0x89, 0x61, 0x8d, 0xd7, 0x8e, 0x1e, 0xc2, 0x5e, 0x5e, 0x38, 0x75, 0x51, 0x62, 0x6a, 0xb1,
	0x54, 0x37, 0xa9, 0x5f, 0x26, 0x1d, 0xae, 0xa1, 0x41, 0xc4, 0x25, 0xc1, 0xe7, 0x4b, 0xf1, 0x23,
	0x74, 0x56, 0xb7, 0x98, 0x00, 0xfb, 0x97, 0x44, 0xff, 0x3e, 0xb9, 0x65, 0xb9, 0xa6, 0x92, 0x33,
	0xde, 0x16, 0xd9, 0x65, 0x89, 0x69, 0xa1, 0x49, 0x3c, 0x55, 0x99, 0x74, 0xb9, 0x6c, 0x86, 0x11,
	0x7f, 0x17, 0x61, 0x72, 0x46, 0x95, 0xa5, 0xb9, 0x4e, 0x1d, 0x96, 0x13, 0xca, 0x26, 0xed, 0x92,
	0x5e, 0x70, 0x86, 0xf1, 0x31, 0x96, 0x93, 0x13, 0x42, 0x47, 0x0a, 0x3a, 0xbf, 0x18, 0x8d, 0xe7,
	0x56, 0x69, 0x2e, 0x84, 0xeb, 0x19, 0x6a, 0xce, 0x9f, 0x6d, 0xc9, 0x63, 0x52, 0x9f, 0x42, 0xe7,
	0xb8, 0x8c, 0xa5, 0x10, 0x26, 0x8c, 0x3a, 0xe7, 0x73, 0xbe, 0xe2, 0xb6, 0x0c, 0x93, 0x80, 0x2e,
	0x7c, 0xc6, 0xb7, 0xc9, 0xe8, 0xc2, 0x67, 0xa3, 0xb7, 0xb0, 0x43, 0x9f, 0xb8, 0xb3, 0xcc, 0x1e,
	0x40, 0x2b, 0x0a, 0x40, 0x7c, 0x7e, 0xc2, 0x2c, 0xec, 0xf4, 0x6a, 0x7c, 0xbe, 0xde, 0xff, 0xd5,
	0xf8, 0x7c, 0xf4, 0xbf, 0x2d, 0x68, 0xff, 0x64, 0x32, 0xe5, 0x29, 0xe0, 0x77, 0x2b, 0x2c, 0x7f,
	0x2a, 0xa6, 0x70, 0xfd, 0x16, 0x11, 0x24, 0x83, 0x0f, 0x4f, 0xa0, 0xe1, 0x97, 0xbc, 0xe9, 0xba,
	0x3e, 0x56, 0xe7, 0x97, 0x0d, 0xbf, 0x24, 0x8f, 0x70, 0xe9, 0x51, 0xe7, 0x31, 0x25, 0xe3, 0x8c,
	0xc4, 0x3b, 0x53, 0xd9, 0x0c, 0x53, 0xe7, 0x95, 0xad, 0xf5, 0x0a, 0x18, 0x1a, 0x13, 0x42, 0xba,
	0x18, 0x08, 0xb4, 0xb6, 0x15, 0x74, 0x91, 0x81, 0xd7, 0x3a, 0x17, 0x7f, 0x84, 0x40, 0x4d, 0xd9,
	0xbd, 0xdd, 0x4f, 0xdd, 0x0b, 0x6b, 0x7f, 0x36, 0x1a, 0x47, 0x1f, 0x60, 0x87, 0xe4, 0x8e, 0x6f,
	0x43, 0x95, 0x25, 0x1f, 0x70, 0x47, 0xf2, 0x98, 0x64, 0x09, 0x97, 0x21, 0x58, 0xdb, 0x92, 0x86,
	0xe2, 0x4b, 0xd8, 0x2e, 0x4d, 0x16, 0x8f, 0x34, 0x8c, 0x5b, 0xd6, 0x41, 0x92, 0x64, 0x1b, 0xfd,
	0xb3, 0x0d, 0x9d, 0x39, 0xa2, 0x4d, 0x73, 0x74, 0x99, 0xf8, 0x03, 0x0c, 0x2e, 0x6e, 0x3c, 0xba,
	0xd4, 0x62, 0x86, 0xc5, 0x15, 0xe6, 0xf1, 0x03, 0x7d, 0x46, 0x65, 0x04, 0xc5, 0xe7, 0x00, 0x81,
	0xe6, 0x50, 0xfb, 0xf8, 0x64, 0x77, 0x18, 0x19, 0xa3, 0x26, 0xa9, 0xeb, 0x94, 0xca, 0x79, 0xda,
	0xe4, 0x2a, 0x7e, 0xfc, 0xd6, 0xd3, 0xdf, 0x26, 0xab, 0xc4, 0xec, 0x6a, 0xc5, 0x74, 0x75, 0x4c,
	0xef, 0x62, 0x8e, 0x29, 0xc4, 0x9f, 0x41, 0x87, 0x52, 0x15, 0x33, 0x8f, 0x39, 0x07, 0xb8, 0x2d,
	0xd7, 0x00, 0x85, 0x83, 0xf4, 0x87, 0x43, 0xdb, 0x91, 0x3c, 0x16, 0x5f, 0xc0, 0x76, 0x36, 0x99,
	0xc6, 0x78, 0xd6, 0x45, 0x1e, 0x44, 0x51, 0x92, 0x45, 0x24, 0xb0, 0x5b, 0xe8, 0x0b, 0xb3, 0xd0,
	0x39, 0xd7, 0x6d, 0x5b, 0xd6, 0x53, 0x31, 0x82, 0x86, 0x56, 0x5c, 0xa1, 0x77, 0xb7, 0x0c, 0x0d,
	0xad, 0xa8, 0x31, 0x29, 0x72, 0x2e, 0xd1, 0xa6, 0x6c, 0x14, 0x1c, 0x93, 0xb5, 0x18, 0x71, 0xed,
	0x75, 0x64, 0x67, 0xa5, 0x41, 0xb7, 0x94, 0xa4, 0xf7, 0x2b, 0x25, 0xf9, 0x0a, 0xfa, 0x51, 0x40,
	0xd2, 0x4b, 0x6d, 0xae, 0x75, 0xd2, 0x0f, 0x3d, 0x44, 0x04, 0xff, 0x4a, 0x98, 0x78, 0x0e, 0x07,
	0x2a, 0xbf, 0x42, 0xeb, 0x0b, 0x87, 0x79, 0xca, 0x0a, 0x43, 0xb2, 0x93, 0x0c, 0xb8, 0xf4, 0xc4,
	0xda, 0x76, 0x46, 0xa6, 0x8f, 0x68, 0xef, 0x14, 0xa8, 0xe1, 0xdd, 0x02, 0xf5, 0x67, 0x78, 0x40,
	0x57, 0x90, 0xce, 0x50, 0xe5, 0x68, 0x5d, 0x3a, 0xb7, 0x38, 0x41, 0x6b, 0x31, 0x4f, 0xf6, 0xd8,
	0x95, 0x03, 0xb2, 0xbe, 0x0d, 0xc6, 0xb3, 0xda, 0x46, 0x4a, 0x72, 0x45, 0x27, 0xce, 0x2e, 0xd7,
	0xf9, 0xb2, 0x1f, 0x94, 0xe4, 0x0a, 0xed, 0x8b, 0xec, 0x72, 0x95, 0x30, 0xdf, 0xc0, 0xf0, 0xba,
	0xf0, 0x1a, 0x9d, 0x4b, 0x51, 0x93, 0xde, 0xe5, 0x89, 0x08, 0xc4, 0x08, 0xbf, 0x0e, 0x28, 0x85,
	0xe2, 0xba, 0xb0, 0x54, 0x27, 0x99, 0xc9, 0xa9, 0x9d, 0xba, 0xc7, 0x0e, 0xf7, 0x08, 0x7c, 0x1d,
	0x31, 0x2a, 0xb7, 0xcd, 0xf6, 0xe0, 0x20, 0x94, 0x9b, 0x5f, 0xf7, 0x06, 0xc7, 0x30, 0x60, 0xc2,
	0x3a, 0x63, 0xee, 0x7f, 0x9a, 0x5b, 0x7d, 0xfa, 0x3f, 0x59, 0xa5, 0xd0, 0x37, 0x30, 0xe4, 0xea,
	0x2d, 0xf4, 0x34, 0x8d, 0x5d, 0xef, 0x03, 0xbe, 0xdc, 0x41, 0x0d, 0xbf, 0x0d, 0xdd, 0xef, 0xe7,
	0x00, 0x9c, 0xb3, 0xe1, 0x39, 0x7d, 0xc8, 0x1c, 0xce, 0xe2, 0xf0, 0x74, 0x3e, 0x87, 0x03, 0x36,
	0x2b, 0xad, 0xcd, 0x42, 0x67, 0x98, 0x47, 0x62, 0xc2, 0x2d, 0xac, 0x20, 0xdb, 0x8b, 0xda, 0x14,
	0x56, 0x3c, 0x85, 0x21, 0xaf, 0x98, 0xd3, 0xa7, 0xb5, 0xd1, 0x19, 0x26, 0xbf, 0x0b, 0x55, 0x47,
	0xf0, 0x59, 0xa1, 0xa7, 0xa7, 0x04, 0x8a, 0x3f, 0xc1, 0x60, 0xcd, 0x23, 0xe7, 0x93, 0x47, 0x9f,
	0x9e, 0xaa, 0x57, 0xaf, 0xa1, 0xe6, 0x87, 0x6e, 0x68, 0xbd, 0xa4, 0x2a, 0x32, 0xea, 0x14, 0x1f,
	0x73, 0xb8, 0x06, 0x35, 0xef, 0x3d, 0xa3, 0xa3, 0x7f, 0xef, 0x40, 0x8f, 0x54, 0x04, 0x3d, 0x89,
	0x98, 0x77, 0xe2, 0x47, 0x78, 0x58, 0x29, 0x7a, 0x4b, 0xb4, 0xd2, 0x19, 0xbd, 0x2a, 0x94, 0x73,
	0xd3, 0x55, 0x2f, 0xdd, 0x96, 0xf7, 0x37, 0xcc, 0xef, 0xf4, 0x59, 0x34, 0x52, 0xd6, 0x6d, 0xae,
	0xdb, 0xe8, 0x66, 0x87, 0x1b, 0x38, 0xbf, 0xf6, 0xdf, 0x81, 0xd8, 0xa4, 0x66, 0x37, 0x59, 0x89,
	0xa1, 0x6d, 0x6c, 0xca, 0xfd, 0x0d, 0xcb, 0x09, 0x1b, 0xc4, 0x09, 0xfc, 0x7e, 0x93, 0xbe, 0xbe,
	0x84, 0xf4, 0xaa, 0x70, 0x85, 0x8f, 0x8d, 0x55, 0x53, 0x3e, 0xde, 0x60, 0xfd, 0x54, 0xdf, 0xcb,
	0xc7, 0x40, 0x11, 0xaf, 0x20, 0x89, 0xb9, 0x13, 0x36, 0xd8, 0xe0, 0xc6, 0x76, 0xeb, 0x56, 0x38,
	0xef, 0x87, 0xac, 0xa2, 0x6d, 0xde, 0xaf, 0x99, 0x24, 0x1d, 0xee, 0x46, 0x67, 0x94, 0xa0, 0xad,
	0x20, 0x1d, 0x71, 0x2a, 0x8e, 0xa0, 0x47, 0xc3, 0xf0, 0x12, 0x60, 0xfe, 0x2b, 0x39, 0xe7, 0x3d,
	0xbb, 0x44, 0x18, 0x07, 0x3b, 0x57, 0x1e, 0xf1, 0x2d, 0x92, 0x27, 0x74, 0x4d, 0x0e, 0x33, 0xa3,
	0x73, 0xc7, 0x9a, 0xb4, 0x2d, 0x0f, 0xc8, 0x2a, 0x6b, 0xe3, 0x38, 0xd8, 0xa8, 0x4f, 0xe2, 0x55,
	0xd9, 0xc2, 0x5a, 0xea, 0x7d, 0x42, 0x8a, 0x75, 0x42, 0xf3, 0x4b, 0x96, 0x93, 0x60, 0x08, 0x09,
	0xf6, 0x18, 0x3a, 0xcc, 0x9e, 0x58, 0x53, 0x45, 0xc5, 0x6a, 0x13, 0xf0, 0xc6, 0x9a, 0x4a, 0x3c,
	0x0c, 0x47, 0x49, 0xbd, 0x61, 0xd1, 0x6a, 0xca, 0x16, 0x4d, 0xcf, 0x0d, 0xbf, 0x05, 0x85, 0xf5,
	0xb3, 0x5c, 0xdd, 0xc4, 0xfd, 0x7b, 0x6c, 0xef, 0xd7, 0x28, 0x6f, 0xfe, 0xf2, 0xeb, 0x9f, 0x47,
	0xd3, 0xc2, 0xcf, 0x16, 0x17, 0x47, 0x99, 0xa9, 0xbe, 0x9f, 0x5f, 0xfa, 0xef, 0x32, 0xe5, 0x66,
	0x34, 0xc8, 0xbf, 0x2f, 0x35, 0xfd, 0xec, 0x3c, 0xbb, 0x68, 0xb1, 0xe2, 0xfc, 0xf0, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x14, 0x12, 0xcf, 0x39, 0x86, 0x0e, 0x00, 0x00,
}
